### ISSUE TITLE
Use Bitcoin Regtest to be able to run end to end tests against a local network

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/ion#108]
As mentioned during the WG meeting, here is a link to learn more about Bitcoin Regtest: https://developer.bitcoin.org/examples/testing.html#regtest-mode

It is possible to run a local bitcoin blockchain locally or in CI, and you can reset its state in between tests

**Comment by thehenrytsai** [comment]
Thanks for adding regtest support!
