### ISSUE TITLE
DID Not Found(v0.10.0 install guide)

### ISSUE THREAD

**Issue by nayuta-ueno** [decentralized-identity/ion#117]
I try [v0.10.0 install guide](https://github.com/decentralized-identity/ion/blob/b2d836ec10c38189a2bb3ef8dfc7e61cd1a6a031/install-guide.md#7-run-ion-core-service), but "DID Not Found".

commit: b2d836ec10c38189a2bb3ef8dfc7e61cd1a6a031

Ubuntu 18.04

```
$ curl http://localhost:3000/identifiers/did:ion:test:EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag
{"code":"did_not_found","message":"DID Not Found"}

$ curl http://localhost:3000/did:ion:test:EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag
```

https://github.com/decentralized-identity/ion/issues/101

**Comment by downTheFallLine** [comment]
I'm able to repro this same issue.    request completes in about 90 msec per postman.   ION node is running out in AWS west, on an Ubuntu 18 image.   log snippet from core follows:


Handling resolution request for: did:ion:test:EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag...
Resolving DID unique suffix 'EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag'...
Refreshing cached blockchain time...
Refreshed blockchain time: {"time":1832398,"hash":"00000000000000a487f8c93413cbe354deceae39807e1ddad68e7ece0c69de47"}
Fetching Sidetree transactions from blockchain service...
Fetching URI 'http://127.0.0.1:3002/transactions'...
Fetch response: 200'.
Fetched 0 Sidetree transactions from blockchain service in 3402 ms.
Successfully kicked off downloading/processing of all new Sidetree transactions.
Fetched 0 unresolvable transactions to retry in 2 ms.
Waiting for 60 seconds before fetching and processing transactions again.
Refreshing cached blockchain time...
Refreshed blockchain time: {"time":1832398,"hash":"00000000000000a487f8c93413cbe354deceae39807e1ddad68e7ece0c69de47"}
Fetching Sidetree transactions from blockchain service...
Fetching URI 'http://127.0.0.1:3002/transactions'...
Fetch response: 200'.
Fetched 0 Sidetree transactions from blockchain service in 3060 ms.
Successfully kicked off downloading/processing of all new Sidetree transactions.
Fetched 0 unresolvable transactions to retry in 1 ms.
Waiting for 60 seconds before fetching and processing transactions again.

**Comment by nayuta-ueno** [comment]
v0.10.0 use http://127.0.0.1:5001/ for IPFS service.
https://github.com/decentralized-identity/ion/blob/b2d836ec10c38189a2bb3ef8dfc7e61cd1a6a031/json/testnet-core-config.json#L6

Maybe, we should start `ipfs daemon` at "[3. Installing Go-IPFS](https://github.com/decentralized-identity/ion/blob/b2d836ec10c38189a2bb3ef8dfc7e61cd1a6a031/install-guide.md#3-installing-go-ipfs)".

But... I'm still getting "DID Not Found"...

**Comment by nayuta-ueno** [comment]
v1.0.0 same.

```
Handling resolution request for: did:ion:test:EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag...
Resolving DID unique suffix 'EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag'...
DID not found for DID 'did:ion:test:EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag'...
```

**Comment by thehenrytsai** [comment]
@nayuta-ueno, apologies for the late response. All pre v1.0 DIDs are wiped. I have just updated the install guide: https://github.com/decentralized-identity/ion/commit/0300d3790b99bb548d32bc4040243c1c4cbea760

Going forward, all DIDs created post v1.0 will be retained.

I am going close this issue since v0.10.0 DIDs are gone. But please feel free to start a new issue. I will try to jump on it this time especially if you @ me.

**Comment by Pantamis** [comment]
Just tried with the updated install guide on mainnet and it worked !
