### ISSUE TITLE
Chrome Plugin Appears to be Broken

### ISSUE THREAD

**Issue by downTheFallLine** [decentralized-identity/ion#125]
Attempted to use the Chrome plugin described at:

https://didproject.azurewebsites.net/docs/install-extension.html

Attempts to read DIDs seems to work, but reports "did not found"---   At least the extension emits a REST Call.

Attempt to create a DID simply results in spinning wheel of death.

**Comment by csuwildcat** [comment]
@downTheFallLine though that plugin may some aspect of it that included use of ION in some way, it is not specifically related to ION or indicative of a problem with ION. The extension's code doesn't live in DIF, so you would have to contact the Microsoft team that developed the extension to inquire about what the problem might be: https://didproject.azurewebsites.net/docs/vc-preview.html

**Comment by downTheFallLine** [comment]
Thanks @csuwildcat.  looks like the feedbank link on the web page is busted.  oh well.

**Comment by csuwildcat** [comment]
@downTheFallLine  not sure what you mean - I clicked the contact email link in the text on that page and it opened up a new email window with Microsoft's ownyouridentity@microsoft.com email address populated in the To: field. That's the email I believe they use for engagement, if you wanted to email them about this.

**Comment by downTheFallLine** [comment]
I thought that was for partnership opportunities, not technical matters.  I will give it a shot and see what happens.  Thanks!

**Comment by thehenrytsai** [comment]
Closing, feel free to reopen as needed.
