### ISSUE TITLE
What is DIF?

### ISSUE THREAD

**Issue by GlenCooper** [decentralized-identity/ion#138]
What is DIF as highlighted here: https://archive.vn/Ls4cn#selection-1549.100-1549.103 ?

A web search didn't help much as I was not about to guess which of these it supposedly meant (if any):
https://acronyms.thefreedictionary.com/DIF

Please at least define it once in the document, like HTML (HyperText Markup Language), or include a hyperlink to a page that defines what it is.

Thanks!

**Comment by csuwildcat** [comment]
DIF is the Decentralized Identity Foundation, the standards/open source development organization this spec is being developed in.
