### ISSUE TITLE
Build steps require `npm install tsc`

### ISSUE THREAD

**Issue by cbeams** [decentralized-identity/ion#140]
Following the instructions in the readme, I got this error:
```
$ npm run build

> ion@1.0.0 build /Users/cbeams/lab/ion
> tsc && copyfiles "json/**/*.json" dist && copyfiles "tests/**/*.json" dist && copyfiles "tests/**/*.js*" dist

sh: tsc: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! ion@1.0.0 build: `tsc && copyfiles "json/**/*.json" dist && copyfiles "tests/**/*.json" dist && copyfiles "tests/**/*.js*" dist`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ion@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cbeams/.npm/_logs/2021-01-29T07_04_53_190Z-debug.log
```

To fix this, I ran `npm install tsc`, after which the previous `npm run build` command worked, as well as the subsequent `npm install -g .`.

```
$ node -v
v14.15.4
$ npm -v
6.14.10
```

**Comment by csuwildcat** [comment]
Is this from the guide? Are you saying the guide is missing an install step? If so, would you be willing to submit a PR?

**Comment by cbeams** [comment]
It’s just from following the steps in the readme of this repository. I’m not an npm expert, so I don’t know if simply adding this to the steps would be the right thing to do.

**Comment by thehenrytsai** [comment]
@cbeams, just wondering was your environment linux or windows?

**Comment by cbeams** [comment]
Mac

**Comment by thehenrytsai** [comment]
PR submitted to include the installation of TypeScript in Linux/Mac: https://github.com/decentralized-identity/ion/pull/185/commits/427df45564fa8295c0f541ad3b0b61378fbefc95
