### ISSUE TITLE
ion-bitcoin microservice failing to start

### ISSUE THREAD

**Issue by mburns** [decentralized-identity/ion#147]
I'm trying to stand up an ION node on Ubuntu v20.04 and am running into issues with the `ion-bitcoin` microservice:

`Error: Fetch failed [500]: {"result":null,"error":{"code":-5,"message":"Invalid address"},"id":"7uo3n8731lv"}`

# Context

I've synced the bitcoin chain (on testnet) and it is up to date, and used the install guide more-or-less verbatim. `bitcoind`, `go-ipfs` and `mongod` are all up and running.

However, when I go to run `npm run bitcoin` (after `npm i` and `npm run build`), it fails with what appears to be `Invalid address`:  https://gist.github.com/mburns/181fb1372e316659d9a7a6e54e7f0416#file-_npm-run-bitcoin-L16

It's not clear where to troubleshoot from here. Am I doing something wrong (probably) or have the install docs gotten out of date with something?

Seems related to #142

**Comment by thehenrytsai** [comment]
From the log it definitely feels like you have supplied an invalid wallet WIF string. Make sure you are not using a mainnet private key against testnet as I believe it won't work.

Perhaps try to generate one from https://learnmeabitcoin.com/technical/wif just to test it, do NOT fund the address you generated from here, especially mainnet addresses.

**Comment by mburns** [comment]
Thanks, this was indeed my problem.
