### ISSUE TITLE
"did_not_found"

### ISSUE THREAD

**Issue by ossobucco** [decentralized-identity/ion#152]
Hi,
I completed the install-guide.md for ION v1.0.1 (using the binary) on Ubuntu 20.02.4 LTS.  The ION Bitcoin microservice and ION core service are plugging away smartly in each of their terminal windows.  However, when I try the mainnet test link

`http://localhost:3000/identifiers/did:ion:EiB18LV2dAdALwCVx10mnLxIFd3XhrlhFOqel7v5wVpNEA`

in Firefox , I get:

`{"code":"did_not_found","message":"DID Not Found"}`

How could this be?  Thanks.

**Comment by csuwildcat** [comment]
@thehenrytsai is this DID outside the genesis block window?

**Comment by nayuta-ueno** [comment]
Maybe, `did:ion:EiB18LV2dAdALwCVx10mnLxIFd3XhrlhFOqel7v5wVpNEA` is [old document](https://github.com/decentralized-identity/ion/commit/0300d3790b99bb548d32bc4040243c1c4cbea760#diff-10dddd5d64417195a85c8e8e41acb6aa2682bb3c8abb06f9e7ac9124fcc10029R196).

Current document is `did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w`.
http://localhost:3000/identifiers/did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w

**Comment by thehenrytsai** [comment]
Correct, this appears to be a pre v1.0 DID, which is no longer supported.

I believe I have also updated install guide to DIDs that are resolvable, I have also just made another search and the DID reference is nowhere to be found in the repo anymore.

With this I am going to close this issue, but please feel free to reopen if you believe this is a mistake!
