### ISSUE TITLE
Unable to build Docker image

### ISSUE THREAD

**Issue by adamjbradley** [decentralized-identity/ion#16]
Unable to build ION using Docker 18.09.2 on Macbook OSX 10.14.3

![image](https://user-images.githubusercontent.com/1193259/57815161-a3aa1a80-77b9-11e9-8540-bd8a04206d50.png)

**Comment by thehenrytsai** [comment]
Are you referring to the `docker-compose.yml` in the [Sidetree repo](https://github.com/decentralized-identity/Sidetree)? Based on your screenshot it looks like you don't have `git` installed?

**Comment by csuwildcat** [comment]
The implementation has been updated with a significant change, from reliance on Bitcore as the Bitcoin node API wrapper to Bcoin. As a result, the Docker build is likely out of date. Please try the updated install guide here: https://github.com/decentralized-identity/ion/blob/master/install-guide.md

**Comment by thehenrytsai** [comment]
Looks like this is an issue for the Sidetree which is tracked [here](https://github.com/decentralized-identity/sidetree/issues/205).
