### ISSUE TITLE
How where to "Add the string ion-bitcore to the services array in the ion-bitcore instance's bitcore-node.json configuration file."

### ISSUE THREAD

**Issue by wksantiago** [decentralized-identity/ion#18]
How where to "Add the string ion-bitcore to the services array in the ion-bitcore instance's bitcore-node.json configuration file."

Thanks,

**Comment by thehenrytsai** [comment]
Do a search under the folder where you installed `bitcored` for the JSON config file. Note that Sidetree-Bitcoin service longer depends on `bitcored` and depends on `bcoin` instead, and this will propagate to ION soon with the appropriate setup guide update, in the mean time you can use [this guide](https://github.com/decentralized-identity/sidetree/tree/master/lib/bitcoin) to setup `bcoin`.

**Comment by thehenrytsai** [comment]
[Setup guide](https://github.com/decentralized-identity/ion/blob/master/install-guide.md) is updated. Please give it a try!

**Comment by thehenrytsai** [comment]
Closing this issue. Bitcored is no longer used.

**Comment by wksantiago** [comment]
Thanks @thehenrytsai
