### ISSUE TITLE
ion-core-mainnet container fails

### ISSUE THREAD

**Issue by cent2sat** [decentralized-identity/ion#183]
I get this error when ion-core-mainnet container tries to start after ion-bitcoin-mainnet synchronizes. 

```
> ion@1.0.1 core /ion

> node dist/src/core.js


Loading core config from /ion/json/mainnet-core-docker-config.json...

Loading core versioning config from /ion/json/mainnet-core-versioning.json...

(node:20) Warning: Accessing non-existent property 'count' of module exports inside circular dependency

(Use `node --trace-warnings ...` to show where the warning was created)

(node:20) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency

(node:20) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency

(node:20) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency

Collection 'service' does not exists, creating...

Collection 'service' created.

Transaction collection does not exists, creating...

Transaction collection created.

Unresolvable transaction collection does not exists, creating...

Unresolvable transaction collection created.

(node:20) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.

(node:20) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.

Upgrading DB from version undefined to 1.0.1...

DB upgraded in: 6 ms.

Refreshing cached blockchain time...

Sidetree node initialization failed with error TypeError: Cannot read property 'toString' of null

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! ion@1.0.1 core: `node dist/src/core.js`

npm ERR! Exit status 1


 

npm ERR! Failed at the ion@1.0.1 core script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:

npm ERR!     /root/.npm/_logs/2021-03-27T22_29_26_514Z-debug.log
```
Additional Info:
```
$ node -v
v14.16.0
$ npm -v
6.14.11
```

**Comment by csuwildcat** [comment]
@thehenrytsai any idea what this might be happening?

**Comment by cent2sat** [comment]
Running ubuntu 18.04 on a new Standard D2s v3 (2 vcpus, 8 GiB memory) VM with additional 1TB SDD attached.
```
$ docker -v
Docker version 20.10.5, build 55c4c88
$ docker-compose -v
docker-compose version 1.28.6, build 5db8d86f
$ nodejs -v
v14.16.0
```

**Comment by thehenrytsai** [comment]
It looks like the Core service is failing because it is not able to fetch blockchain time from Bitcoin service thus failing initialization. Maybe make sure the Bitcoin service is indeed up and running. @mahoekst might be able to add more suggestions as he was the author of the `docker-compose`

**Comment by cent2sat** [comment]
Bitcoin is indeed up and running. Took about 24-26hrs to sync. 
```
$ ./deploy-docker-mainnet.sh 
SETTING UP MAINNET CONFIGURATION FOR ION
Please enter the directory for storing the bitcoin blockchain data: /mnt/disk/bitcoin
Please enter the directory for storing data for the mongo service: /mnt/disk/db
Please enter the directory for storing data for the IPFS service: /mnt/disk/ipfs
creating containers without starting.
mongo
ipfs
creating config files
Starting up bitcoin-node service
bitcoin-core-mainnet
Bitcoin-core-mainnet started, please wait for this to complete a sync before proceeding
Run "docker logs -f bitcoin-core-mainnet" to tail the current logs from the node in another session to track progress
When the logs show an entry like "2020-07-08T03:39:41Z UpdateTip: new best=00000000324c4621bdba9b3c8f034dbe1086f643dbf1eb4f609174c8e384acca height=1534 version=0x00000001 log2_work=42.584045 tx=2476 date='2012-05-25T17:17:13Z' progress=1.000000 cache=0.3MiB(1771txo)" ending with "progress=1.00000" the sync is complete

Please be patient. It takes a minute before the syncing starts and after that it can take up to 24 hours to download the entire database.


Starting ion-bitcoin, please wait the service finish scanning the bitcoin blockfiles before proceeding 

Run " docker logs -f ion-bitcoin" to tail the current logs from the node 

When the log shows an entry like " bla bla " the sync is complete 
ion-bitcoin-mainnet

Starting ion-node
ion-core-mainnet
Congratulations. Your ION node is running connected to bitcoin mainnet. Happy resolving
```

**Comment by thehenrytsai** [comment]
Guess I need to clarify, Bitcoin Core `bitcoin-core-mainnet` is different to ION Bitcoin service (`ion-bitcoin`), I was referring to the `ion-bitcoin`, so try to do `docker logs -f ion-bitcoin` to tail its current logs to sanity verify that it is indeed up and running, I am guess there are some issues with it.

> When the log shows an entry like " bla bla " the sync is complete

This clearly contains a place-holder text, I am going to update the " bla bla " text to "Sidetree-Bitcoin node running on port:" right now.

**Comment by cent2sat** [comment]
ion-bitcoin-mainnet log repeats

```
Starting periodic polling for the lock monitor.

Refreshed the in-memory value time lock state.

Ending periodic polling for the lock monitor.
```

**Comment by thehenrytsai** [comment]
Yeah... ION Bitcoin doesn't look like in the right state. Are you able to restart the ION Bitcoin service container to see what happened (in the logs) during startup/initialization?

**Comment by cryptolinux** [comment]
@thehenrytsai I am confused, ion-core-mainnet container fails. Do you guys need help? I could offer it to Microsoft, but if your team is not capable of having a discussion with slandering, your profile says you work for Microsoft, then please tell me who at Microsoft gave ok for this project or anybody who can confirm it?

Also, we have to tell users not to buy ion, Microsofts failure on proper communication leads to issues for us, and for you. Please engage in talk.

For the question about ion core and main net, it is located here: https://github.com/ioncoincore/ion

I dislike if somebody looking for our project lands here by looking for ion core.

**Comment by cryptolinux** [comment]
@thehenrytsai despite your colleague claiming things, we have token system on ion since quite long, before you guys even started this project. You have my email, contact me please if you want to resolve this in the way it is normaly done, neither we nor you nor Microsoft wants to have such discussion public.

**Comment by mahoekst** [comment]
> ion-bitcoin-mainnet log repeats
> 
> ```
> Starting periodic polling for the lock monitor.
> 
> Refreshed the in-memory value time lock state.
> 
> Ending periodic polling for the lock monitor.
> ```

Did you do a new install or an update? I have seen this when the config file was the old version as well.

When I start my ion-core-mainnet container and the bitcoin-core-mainnet container is not done syncing the blocks yet I typically see this error message:
Loading core config from /ion/json/mainnet-core-docker-config.json...
Loading core versioning config from /ion/json/mainnet-core-versioning.json...
Collection 'service' found.
Transaction collection already exists.
Unresolvable transaction collection already exists.
(node:18) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:18) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
Refreshing cached blockchain time...
Sidetree node initialization failed with error FetchError: request to http://ion-bitcoin-mainnet:3002/time failed, reason: getaddrinfo EAI_AGAIN ion-bitcoin-mainnet ion-bitcoin-mainnet:3002
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ion@1.0.1 core: `node dist/src/core.js`
npm ERR! Exit status 1
npm ERR! Failed at the ion@1.0.1 core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-29T07_29_09_779Z-debug.log
> ion@1.0.1 core /ion
> node dist/src/core.js

What is the config file you are using for ion-core-mainnet look like? And is it referenced correctly from the container?

**Comment by cent2sat** [comment]
@mahoekst Just started a fresh install of ubuntu 18.04 only reusing the bitcoin data directory.

Once the bitcoin blockchain reaches progress=1.000000 the ion-bitcoin-mainnet container starts but the logs only repeat 

```
Starting periodic polling for the lock monitor.
Refreshed the in-memory value time lock state.
Ending periodic polling for the lock monitor.
```

Followed the instructions located at ion/docker/README.md while using the configuration files below:

ION_BITCOIN_CONFIG_FILE_PATH | /ion/json/mainnet-bitcoin-docker-config.json
ION_BITCOIN_VERSIONING_CONFIG_FILE_PATH | /ion/json/mainnet-bitcoin-versioning.json

**Comment by mahoekst** [comment]
Could you paste your config (without the RPCPassword?)

**Comment by cent2sat** [comment]
https://github.com/decentralized-identity/ion/blob/master/json/mainnet-bitcoin-docker-config.json

**Comment by mahoekst** [comment]
very strange, assuming the RPC password is correct. No clue why it won't start.

**Comment by mahoekst** [comment]
What's the end of your main bitcoin node log file look like?

**Comment by cent2sat** [comment]
```
2021-03-31T02:56:38Z UpdateTip: new best=0000000000000000000955f8bc35717d617d4504d16bdf635cff177d0f085279 height=677081 version=0x3fffe000 log2_work=92.774844 tx=629660386 date='2021-03-31T02:56:42Z' progress=1.000000 cache=134.6MiB(985717txo) warning='67 of last 100 blocks have unexpected version'


2021-03-31T02:59:43Z UpdateTip: new best=00000000000000000000f54d2b3e01cd8a50c994a25d050a81db5a5cd2b0c700 height=677082 version=0x20800000 log2_work=92.77486 tx=629661981 date='2021-03-31T02:59:20Z' progress=1.000000 cache=134.9MiB(988582txo) warning='68 of last 100 blocks have unexpected version'


2021-03-31T03:00:27Z UpdateTip: new best=00000000000000000000e379818fb7d865cdc13de674675408f1a12b7890bffb height=677083 version=0x37ffe000 log2_work=92.774876 tx=629662336 date='2021-03-31T03:00:07Z' progress=1.000000 cache=135.0MiB(989313txo) warning='69 of last 100 blocks have unexpected version'


2021-03-31T03:07:51Z UpdateTip: new best=000000000000000000002f76b901642b3df1084c955cb66d86c407ee12921084 height=677084 version=0x20800000 log2_work=92.774892 tx=629663532 date='2021-03-31T03:07:35Z' progress=1.000000 cache=135.9MiB(996300txo) warning='69 of last 100 blocks have unexpected version'


2021-03-31T03:21:07Z Pre-allocating up to position 0xa00000 in rev02516.dat


2021-03-31T03:21:07Z UpdateTip: new best=000000000000000000056db0cd3bf44a92bf91476e8e290ab3fdc6c238a486c8 height=677085 version=0x20800000 log2_work=92.774908 tx=629664731 date='2021-03-31T03:21:02Z' progress=1.000000 cache=136.5MiB(1001273txo) warning='69 of last 100 blocks have unexpected version'


2021-03-31T03:22:55Z UpdateTip: new best=0000000000000000000725ca968b0fa4aeb062b4edbfd65fd9fbc8f3e9d57578 height=677086 version=0x37ffe000 log2_work=92.774924 tx=629665595 date='2021-03-31T03:22:16Z' progress=1.000000 cache=136.7MiB(1002943txo) warning='69 of last 100 blocks have unexpected version'


2021-03-31T03:29:12Z UpdateTip: new best=0000000000000000000783b2910f65ab477e94760fd7638309134d689df6465e height=677087 version=0x2000e000 log2_work=92.77494 tx=629666563 date='2021-03-31T03:29:07Z' progress=1.000000 cache=136.9MiB(1004770txo) warning='70 of last 100 blocks have unexpected version'


2021-03-31T03:32:55Z UpdateTip: new best=00000000000000000000ebbe4cef10bc46b24cf24d54a9afffa763990bb87920 height=677088 version=0x2fffe000 log2_work=92.774956 tx=629667222 date='2021-03-31T03:32:37Z' progress=1.000000 cache=137.1MiB(1006419txo) warning='70 of last 100 blocks have unexpected version'


2021-03-31T03:53:04Z UpdateTip: new best=00000000000000000007fb7174c6baf3ff5c6c6e46df2ec4aa09d0ed67b791be height=677089 version=0x27ffe000 log2_work=92.774972 tx=629669462 date='2021-03-31T03:52:39Z' progress=1.000000 cache=138.2MiB(1014899txo) warning='71 of last 100 blocks have unexpected version'
```

**Comment by mahoekst** [comment]
That looks good as well. IPFS and Mongo are running as well I assume. No clue why ion bitcoin won't start. @thehenrytsai  you have any idea what might be wrong?

**Comment by mahoekst** [comment]
This is the logfile I see when starting:

> ion@1.0.1 bitcoin /ion
node dist/src/bitcoin.js
Loading configuration from /ion/json/mainnet-bitcoin-docker-config.json...
Loading ION bitcoin versioning config from /ion/json/mainnet-bitcoin-versioning.json...
Creating bitcoin wallet using the import string passed in.
Sidetree bitcoin service configuration:
Collection 'service' found.
llection 'blocks' found.
Transaction collection already exists.
Checking if bitcoin contains a wallet for 1CC3X2gu58d6wXUWMffpuzN9JAfTUWu4Kj
Checking if bitcoin wallet for 1CC3X2gu58d6wXUWMffpuzN9JAfTUWu4Kj exists
Sending jRPC request: id: 1cgr5qsubp2, method: getaddressinfo
Wallet found.
Locks collection already exists.
(node:25) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:25) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
Trimming all block and transaction data after block height: undefined
Getting hash for block 667000
Sending jRPC request: id: 3upnl0gvnmg, method: getblockhash
Sending jRPC request: id: 5374elphac5, method: getblockheader
Synchronizing blocks for sidetree transactions...
Starting block: 667000 (0000000000000000000bfc4add1faa645bed3add5486882966c13b29b0e82cdd)
Getting current block height...
Sending jRPC request: id: 7tpbuqrhbnt, method: getblockcount
Getting hash for block 677159
Sending jRPC request: id: 1okug3vq73s, method: getblockhash
Sending jRPC request: id: 50lcc4tkmkf, method: getblockheader
Begin fast processing block 667000 to 677159
Parsing file: blk02517.dat

**Comment by thehenrytsai** [comment]
@cent2sat, are you able to restart the ION Bitcoin service container paste the log from the very beginning during startup/initialization here?

**Comment by cent2sat** [comment]
Once ion-bitcoin-mainnet restarts the logs just show the below in an endless loop. Can anyone start a fresh VM and follow the procedure located ion/docker/README.md to see if it works
```
Starting periodic polling for the lock monitor.

Refreshed the in-memory value time lock state.

Ending periodic polling for the lock monitor.

Starting periodic polling for the lock monitor.

Refreshed the in-memory value time lock state.

Ending periodic polling for the lock monitor.

Starting periodic polling for the lock monitor.

Refreshed the in-memory value time lock state.

Ending periodic polling for the lock monitor.

Starting periodic polling for the lock monitor.

Refreshed the in-memory value time lock state.

Ending periodic polling for the lock monitor.
```

**Comment by thehenrytsai** [comment]
@cent2sat, thanks for the speedy response. I understand the repeated logs from the loop that you are seeing, but was hoping to see the very beginning of the logs from when you first start/restart the service, which could give us direct insights as to what is different from yours and @mahoekst's setup. If it is still unclear after seeing the beginning portion of the logs, I'd be happy to try to repro this myself.

**Comment by cent2sat** [comment]
ion-bitcoin-mainnet logs starting
```
# docker logs f4ff4b4e37ce

> ion@1.0.1 bitcoin /ion
> node dist/src/bitcoin.js

Loading configuration from /ion/json/mainnet-bitcoin-docker-config.json...
Loading ION bitcoin versioning config from /ion/json/mainnet-bitcoin-versioning.json...
Creating bitcoin wallet using the import string passed in.
Sidetree bitcoin service configuration:
(node:18) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:18) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:18) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
Collection 'service' found.
Collection 'blocks' found.
Transaction collection already exists.
Checking if bitcoin contains a wallet for 1CC3X2gu58d6wXUWMffpuzN9JAfTUWu4Kj
Checking if bitcoin wallet for 1CC3X2gu58d6wXUWMffpuzN9JAfTUWu4Kj exists
Sending jRPC request: id: 37qr1pu790e, method: getaddressinfo
Wallet found.
Locks collection already exists.
(node:18) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:18) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
Transaction observer is disabled.
Starting periodic polling for the lock monitor.
Refreshed the in-memory value time lock state.
Ending periodic polling for the lock monitor.
Sidetree-Bitcoin node running on port: 3002
Starting periodic polling for the lock monitor.
Refreshed the in-memory value time lock state.
Ending periodic polling for the lock monitor.
Starting periodic polling for the lock monitor.
Refreshed the in-memory value time lock state.
Ending periodic polling for the lock monitor.

```

**Comment by thehenrytsai** [comment]
> Transaction observer is disabled.

For some reason your transaction observer appears to be disabled.

Please check that `transactionPollPeriodInSeconds` in your `mainnet-bitcoin-config.json` is not set to 0, 60 is a good number to use and should have already been the default.

**Comment by thehenrytsai** [comment]
I just checked commit history, one explanation could be that you have not synced up to the latest, and this config variable was introduced to the docker config on 2020/02/02. Please `git pull` to use latest (or v1.0.1 is fine).

**Comment by cent2sat** [comment]
@thehenrytsai Yep transaction observer was disabled in mainnet-bitcoin-docker-config.json

https://github.com/decentralized-identity/ion/pull/192

**Comment by cent2sat** [comment]
@csuwildcat @mahoekst @thehenrytsai @mburns :+1: :fire:

Thank you for all your help. Glad to announce that all containers are up and running properly.

Please review and then merge pull request https://github.com/decentralized-identity/ion/pull/192

**Comment by thehenrytsai** [comment]
Thanks @cent2sat for testing and providing a fix in a PR!! I have already approved and merged in your PR.

Closing this one now. Please do not hesitate to open new issues as needed!
