### ISSUE TITLE
Why are active issues deleted?

### ISSUE THREAD

**Issue by cryptolinux** [decentralized-identity/ion#187]
![image](https://user-images.githubusercontent.com/20006483/113029449-be5ac200-918c-11eb-8dfa-df8cca403703.png)

@csuwildcat Daniel, I guess you have no explanation, then leave it empty. I suggest here as an issue to change your projects name and the reasons for that are listed above and I have no understand why you close and delete this issue, guess you are failing again and again, lying is bad, it gets you as soon as lies have to start running, their legs brake.

**Comment by cryptolinux** [comment]
Some addition, it does not disappear: https://web.archive.org/web/20210330172204/https://github.com/decentralized-identity/ion/issues/187

**Comment by csuwildcat** [comment]
You are engaged in targeted harassments and attempting to attack parties that have nothing to do with the personal views one individual espouses on social media. Beyond your misunderstanding of the project in question, your behavior here violates the Code of Conduct for interactions in the DIF community and channels. Your issues will be dealt with in accordance with the standards of conduct set forth in this community. I advise you to cease attacking individuals here and leave any discussions of the sort to social mediums where they are taking place.

**Comment by cryptolinux** [comment]
How and who did I harrass?
How and who did I attack?
Your personal view regarding why Microsoft releases a project with same name, you even did not need to comment, it can be sorted out by Microsoft, they are big enough.

It was you who is slandering and you are driving it now into offtopic, you try to hide now behind you making silly statements as private person about a project where you are Main dev, sorry, but it is you who uses this platform to harrass me and your team was not capable to get in touch despite several team members trying to contact you.

This is issue suggesting that you rename your project simple as that, and what you do? You delete it. Says a lot about this project, its lead devs and Microsofts involvement.

**Comment by csuwildcat** [comment]
You are harassing a community member for the personal technology views they espouse on Twitter. Neither organization has anything to do with the philosophical or technical views of any person outside of them. I again advise you to cease attacking individuals here and take your discussion to social media, if you still desire to continue it.

**Comment by cryptolinux** [comment]
Mr. Bucher, I kinda you ask you to explain who and how was harrased

**Comment by nembal** [comment]
Dear @cryptolinux,

It seems that the issue you are raising is personal in nature and is not relevant for improving this work item.
Please consider discussing personal issues in a personal matter. 

Thank you for your understanding,
