### ISSUE TITLE
DID not resolving after multiple blocks

### ISSUE THREAD

**Issue by sondreb** [decentralized-identity/ion#195]
I submitted an DID Document based upon the ION Tools, I manually set all the keys, so it produces the same DID every time. I had to wait a while for the next block, but after it was mined it still does not resolve my short form DID.

I did get the "Successful registration" message in the browser console.

![image](https://user-images.githubusercontent.com/309938/114719983-e4a96180-9d37-11eb-9401-6cb6fe0d0873.png)

Here is the DID in question that returns "DID Not Found":

https://beta.discover.did.microsoft.com/1.0/identifiers/did:ion:EiBodPw-I3MC-Dfn-0pyK3UqlwHa9OqexA98d9GqTsTISw

Here is the long form:

https://identity.foundation/ion/explorer/?did=did%3Aion%3AEiBodPw-I3MC-Dfn-0pyK3UqlwHa9OqexA98d9GqTsTISw%3AeyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJrZXktMSIsInB1YmxpY0tleUp3ayI6eyJjcnYiOiJzZWNwMjU2azEiLCJrdHkiOiJFQyIsIngiOiJpaDNnOUp0SUc2Ulh0aVhkWWdvSWRCS042VFJIQzhJUEpnQ0xiU2lLV0FJIiwieSI6IkpwRl9SQWpDbGVaVDhsTHl5dmpOMUFUU3pGZGtEZVVrVVpiOGs1WDh4WU0ifSwicHVycG9zZXMiOlsiYXV0aGVudGljYXRpb24iXSwidHlwZSI6IkVjZHNhU2VjcDI1NmsxVmVyaWZpY2F0aW9uS2V5MjAxOSJ9XSwic2VydmljZXMiOlt7ImlkIjoiZG9tYWluLTEiLCJzZXJ2aWNlRW5kcG9pbnQiOiJodHRwczovL3d3dy5zb25kcmViLmNvbSIsInR5cGUiOiJMaW5rZWREb21haW5zIn1dfX1dLCJ1cGRhdGVDb21taXRtZW50IjoiRWlCSHFxNlRTSW5PbGZOdHhzeGxxWGlWZnA5eFptNlVfN2ZsbUtWMEg4SzM1QSJ9LCJzdWZmaXhEYXRhIjp7ImRlbHRhSGFzaCI6IkVpQ2dxMWhVNjJnd0h0VWVFbjFQbUpwczBMTDZZTkNLMG5qSWwtOXgtU3NMWlEiLCJyZWNvdmVyeUNvbW1pdG1lbnQiOiJFaURPai14NmFfLThNNWE5Yjc4OWdsbFNGZlQteE9rdmNQcHlVUWVicElpVFVRIn19

Am I missing something? How long will it take after the first block to be able to resolve the short form? Is it because there is a queue of transactions and the ION one is probably not included yet? Is there a way to query an explorer to see the transactions with the attestation?

**Comment by csuwildcat** [comment]
@sondreb could take a few hours, depending on how our daily spend on txns is going, because we spread out our node's writes over the day according to a daily allotment of money. Sometimes that means waiting a while, but the good thing is that long-form DIDs are fully usable while you wait.

**Comment by csuwildcat** [comment]
Also, I am working on getting a few ION node REST APIs added that will allow you to have more visibility into all this. I am not sure how far out those are, but @isaacJChen and @thehenrytsai may be able to provide better estimates.

**Comment by TomCJones** [comment]
This has been a problem I alway expected with the short form DID.  I continue to oppose the whole idea of equivalence as being too ambiguous to be practical.

**Comment by csuwildcat** [comment]
@sondreb it is now anchored and published throughout the network: https://identity.foundation/ion/explorer/?did=did%3Aion%3AEiBodPw-I3MC-Dfn-0pyK3UqlwHa9OqexA98d9GqTsTISw

**Comment by csuwildcat** [comment]
@TomCJones  there's nothing wrong with equivalence and using that as a means to allow use while truly decentralized systems finalize their consensus. Equivalence also allows for evolution of the logical IDs themselves over time, which is something people have started asking about in threads like this, where the alternative is literally forking their entire DID Method and abandoning all DIDs of users, which is just a comically catastrophic non-option:  https://github.com/w3c/did-core/issues/715#issuecomment-812166926. We're doing the hard thinking a decade ahead of where implementers are now so they won't end up with terrible scenarios and broken methods in the future.

**Comment by csuwildcat** [comment]
@sondreb  in the future, at least for our node, we will likely expose a way to pay to get your op in the very next block instead of waiting for larger intervals. This is something we expect to have available as we get more companies who want to pay, which will trickle down to cheaper next-block writes for all users.

**Comment by sondreb** [comment]
Thanks for all the comments and info! Suggest it being added to the FAQ or somewhere that it might take a while to get attested, at least more than a single block.

**Comment by csuwildcat** [comment]
@sondreb I can add that to the ION Tools repo, but do note that it's just because Microsoft's node, which does the anchoring for free, is set to a longer interval to save money. We are probably going to ramp that to like 6 blocks, but in the future, when we have lots of fee-offsetting traffic that pays tiny amounts, together that will let us write every block, as you would probably prefer.
