### ISSUE TITLE
ION bitcoin processor transaction pooling loop uses 100% CPU 

### ISSUE THREAD

**Issue by rossi-d** [decentralized-identity/ion#202]
I'm using the docker deployement of ION, mainnet, and my the docker container "ion-bitcoin-mainnet" logs non stop, no delay between each loop:
`Starting periodic polling for the lock monitor.,
Refreshed the in-memory value time lock state.,
Ending periodic polling for the lock monitor.,
`
Some deepdive in the code tell me that pooling should happen every 60s, but this is obviously not happening.
I'm using the version 0.21 of bitcoin core. Could that be the reason? Else everything works just fine.

**Comment by thehenrytsai** [comment]
@rossi-d, thanks for reporting the issue!

v0.21 bitcoin core is definitely fine. I have a theory and a fix to the problem, basically there are a number of config values missing in the docker script, one of which is the lock monitor polling duration (typically set to 600 seconds). If it's not set, it probably would be defaulted to zero, making the loop to repeat instantly.

You can take a look at the PR #204 and manually add those missing config parameters into `mainnet-bitcoin-docker-config.json`, or you can wait until the PR is approved and redeploy the ION Bitcoin service.

**Comment by rossi-d** [comment]
Thanks. I'll try that.

**Comment by rossi-d** [comment]
@thehenrytsai I can confirm your theory. I manually add the missing params and it's working perfectly fine now. Thanks!
