### ISSUE TITLE
Error: Invalid Address (testnet)

### ISSUE THREAD

**Issue by lemoustachiste** [decentralized-identity/ion#208]
Hey there,

I'm new to ION but I've set up the environment as described in the setup guide.
I looked at #147, while the error is similar I don't think it is the same.

I am trying to set up a testnet environment. For that purpose I am generating an private key from a mnemonic and then the address. I am left with the WIF string. When passing the information into this page, I am finding the expected data: https://gobittest.appspot.com/PrivateKey.

Here are the key pieces of information generated from this process:
```
mnenomic phrase generated:
prevent level element robot buyer area quick harbor input estate wrong unfair

seed: e629fb41081e6f9825bf26b5e2e5cf894b54ee3bd79d37d75166671bb7d9b35b9a19b06405c523f8ff2fa1e5d66f168beb1747052ed3b14289f2ff2aefbc7c48

private key bip32 generated: 363af69bfd9910a22fdc33e7be5f85e74baae48efc01682e8ffaf94b66410f22
public key bip32 generated: 03ebf24a2485cbecf2504fd867af4df240d75afdf51f99fadc669ca6911aac987e
WIF: Ky38MKhMTEL2DvLGGPtZ4G5DzmnwSADBov9zB36M1jyR3eN7J1y8
bitcoin address generated: mgdWjvq4RYAAP5goUNagTRMx7Xw534S5am
```

Here is the log before getting to the error (I've hijacked sidetree to get a more verbose output):
```
Environment variable ION_BITCOIN_CONFIG_FILE_PATH undefined, using default path ../json/testnet-bitcoin-config.json instead.
Environment variable ION_BITCOIN_VERSIONING_CONFIG_FILE_PATH undefined, using default ION bitcoin versioning config path ../json/testnet-bitcoin-versioning.json instead.
Creating bitcoin wallet using the import string passed in.
bitcoinWalletImportString Ky38MKhMTEL2DvLGGPtZ4G5DzmnwSADBov9zB36M1jyR3eN7J1y8
wallet private key 363af69bfd9910a22fdc33e7be5f85e74baae48efc01682e8ffaf94b66410f22
wallet address Network {
  name: 'livenet',
  alias: 'mainnet',
  pubkeyhash: 0,
  privatekey: 128,
  scripthash: 5,
  bech32prefix: 'bc',
  xpubkey: 76067358,
  xprivkey: 76066276,
  networkMagic: <Buffer f9 be b4 d9>,
  port: 8333,
  dnsSeeds: [
    'seed.bitcoin.sipa.be',
    'dnsseed.bluematt.me',
    'dnsseed.bitcoin.dashjr.org',
    'seed.bitcoinstats.com',
    'seed.bitnodes.io',
    'bitseed.xf2.org'
  ]
}
public key hex 03ebf24a2485cbecf2504fd867af4df240d75afdf51f99fadc669ca6911aac987e
```

So while the private and public keys are correctly retrieved from the WIF, the network and address are incorrect.
Indeed, I am expecting `mgdWjvq4RYAAP5goUNagTRMx7Xw534S5am` while sidetree seems to be looking up:
`Checking if bitcoin wallet for 127ZSsk5cWiubyDBkocJdW9dFYLN5N1jHF exists`. Since it's prefixed by `1` , I assume it does not register that I am actually working with testnet.

I couldn't find any other configuration option than the config file path to say this should be testnet.

Here is the content of the testnet-bitcoin-config.json:
```
{
  "bitcoinDataDirectory": "/Users/julien/work/bitcoin/testnet3",
  "bitcoinFeeSpendingCutoffPeriodInBlocks": 1,
  "bitcoinFeeSpendingCutoff": 0.001,
  "bitcoinPeerUri": "http://localhost:18332",
  "bitcoinRpcUsername": "lemoustachiste",
  "bitcoinRpcPassword": "the-password",
  "bitcoinWalletOrImportString": "Ky38MKhMTEL2DvLGGPtZ4G5DzmnwSADBov9zB36M1jyR3eN7J1y8",
  "databaseName": "ion-testnet-bitcoin",
  "genesisBlockNumber": 1900000,
  "logRequestError": true,
  "mongoDbConnectionString": "mongodb://localhost:27017/",
  "port": 3002,
  "sidetreeTransactionFeeMarkupPercentage": 1,
  "sidetreeTransactionPrefix": "ion:",
  "transactionPollPeriodInSeconds": 60,
  "valueTimeLockUpdateEnabled": false,
  "valueTimeLockAmountInBitcoins": 0,
  "valueTimeLockPollPeriodInSeconds": 600,
  "valueTimeLockTransactionFeesAmountInBitcoins": 0.0001
}
```

Again I am very new to ION so I may have missed something obvious. 

Thanks for your help

**Comment by thehenrytsai** [comment]
Hi @lemoustachiste,

What is the actual error?

Judging from the following info in your description, I suspect this is more of a Bitcoin Core configuration issue:

```
 alias: 'mainnet',
```

Please make sure you Bitcoin Core client is configured to run in testnet, see [this section](https://github.com/decentralized-identity/ion/blob/master/install-guide.md#installing-bitcoin-core-manually) of the guide.

To sanity verify you Bitcoin Core setup, you should be able to get an expected response back from any POST RPC request to `http://<username>:<password>localhost:18332` endpoint, such as

{
    "method": "getblockcount"
}

**Comment by lemoustachiste** [comment]
Hi @thehenrytsai,

thanks for your answer. 

Sorry I didn't make the error clear enough, the error is `Invalid Address`, when looking up the aforementioned address. 

I have spent some more manually setting up bitcoin with this guide: https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md. I have things running, but I am still experiencing issues, the main of which is that the address being generated to be looked up with the info is by default on `mainnet` and not `testnet` as I would like it to be.

Here is the bitcoin.conf file I have associated with bitcoin-core:
```
testnet=1
server=1
datadir=~/.bitcoin
rpcuser=lemoustachiste
rpcpassword=mypassword
txindex=1
```

I have checked both with cURL and the ION engine that I have access to localhost:18332 (I was getting a 401 until I updated the ION config with new credentials). I have a wallet created and imported the public key used in the first post.

The issue I am getting now is:

```
Collection 'service' found.
Collection 'blocks' found.
Transaction collection already exists.
Checking if bitcoin contains a wallet for 127ZSsk5cWiubyDBkocJdW9dFYLN5N1jHF
Checking if bitcoin wallet for 127ZSsk5cWiubyDBkocJdW9dFYLN5N1jHF exists
{"method":"getaddressinfo","params":["127ZSsk5cWiubyDBkocJdW9dFYLN5N1jHF"],"jsonrpc":"1.0","id":"76ri0ugi32l"}
url http://localhost:18332
Sending jRPC request: id: 76ri0ugi32l, method: getaddressinfo
Error: Fetch failed [500]: {"result":null,"error":{"code":-5,"message":"Invalid prefix for Base58-encoded address"},"id":"76ri0ugi32l"}

    at BitcoinClient.<anonymous> (/Users/julien/work/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinClient.js:680:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/julien/work/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinClient.js:5:58)
```

I believe it's because it's looking up `127ZSsk5cWiubyDBkocJdW9dFYLN5N1jHF` and not `mgdWjvq4RYAAP5goUNagTRMx7Xw534S5am`, as I am mentioning in the first post. Is there some kind of specific parameter to tell ION or Sidetree to work with testnet and not mainnet?

**Comment by lemoustachiste** [comment]
actually let me do some more digging, it seems my wallet import string is not testnet

**Comment by lemoustachiste** [comment]
Yep that was the issue, I was not generating the WIF for testnet. 

Sorry for the noise.
