### ISSUE TITLE
How to create a batch of dids?

### ISSUE THREAD

**Issue by thomas-tran** [decentralized-identity/ion#210]
In your Q & A section, 
Each newly created ID will pay a transaction fee?
With ION can fit 10,000 ID operations in a single bitcoin transaction.

Can you explain more detail on this? Assume that the company requires to create 1000 DIDs for IOT devices. Does it cost only a single bitcoin transaction or 1000 transactions? How can I do create them in a batch?

Thanks

**Comment by henkvancann** [comment]
To create 1000 DIDs for IOT devices, you wouldn't need 1000 BTC transactions, but only a fraction. Furthermore costs can be shared among many users. e.g. ION is able to bundle thousands of pluriform identifier events in a Merkletree-like structure and only the root hash will be anchored on the bitcoin blockchain. In your specific question, it depends whether you're able to batch the inception events of the IoT identifiers or not. A batch of 1000 identifiers requires 1 BTC transaction and there's even more room in that ION batch. 1000 consecutive inception events over of period of time, could require 1000 BTC transactions, but of course a single identifier event in one anchoring ION BTC transaction should not have to pay for the total fee. The fee can be shared and divided by the number of participating  controllers in that specific ION anchoring BTC transaction.
How can I do create them in a batch? -> Use a Sidetree based solution like ION or ORB.

**Comment by thomas-tran** [comment]
@henkvancann  Thanks for the explanation. 
@csuwildcat Do you have any idea how to batch the request for thousand of identities in ION technically?

**Comment by csuwildcat** [comment]
@thomas-tran pretty sure the node already ships set to batch requests, so if you wanted to batch then write, you'd use the API to send your running node N number of ops, then it will batch them up for you and anchor them (assuming you attach a funded wallet that can do txns). There's one big caveat: anchoring thousand of ION ops is going to require you to have enough in the wallet to lock an escrow-like proof of fee, which uses a relative timelock that will freeze a large amount of Bitcoin for roughly 30 days. It's a form of spam protection for the network. You can so 100 ops in a Bitcoin txn without any proof of fee value lock. @TheHenryTsai please confirm

**Comment by csuwildcat** [comment]
@thomas-tran this doc explains the value locking proof of fee requirement the nodes all enforce: https://github.com/decentralized-identity/ion/blob/master/docs/design.md#value-locking-algorithm

**Comment by thomas-tran** [comment]
> @thomas-tran pretty sure the node already ships set to batch requests, so if you wanted to batch then write, you'd use the API to send your running node N number of ops, then it will batch them up for you and anchor them (assuming you attach a funded wallet that can do txns). There's one big caveat: anchoring thousand of ION ops is going to require you to have enough in the wallet to lock an escrow-like proof of fee, which uses a relative timelock that will freeze a large amount of Bitcoin for roughly 30 days. It's a form of spam protection for the network. You can so 100 ops in a Bitcoin txn without any proof of fee value lock. @thehenrytsai please confirm

@csuwildcat can you point me to the right API or source code that allow to batch no of create operations e.g. I need to create 100 did at once. 

I've checked the source code and I found this information. However, I assume that this only handle 1 did create request at the time.

https://github.com/decentralized-identity/ion/blob/master/src/core.ts
const router = new Router();
router.post('/operations', async (ctx, _next) => {
  const response = await sidetreeCore.handleOperationRequest(ctx.body);
  setKoaResponse(response, ctx.response);
});

**Comment by thehenrytsai** [comment]
@thomas-tran, assuming you are running your own node, you simply need to submit 100 create operations to your node (ie. `http://localhost:3000/operations`) before your batch writer kicks in every 10 minutes by default, the batch writer will batch all 100 operations into 1 bitcoin transaction thus you'll pay fee for just one transaction to the minor.

The technical spec for constructing a create request can be found in [Sidetree API spec](https://identity.foundation/sidetree/api/#create), but if you know TypeScript, you are better off using the [ion-sdk](https://github.com/decentralized-identity/ion-sdk) directly, it will save you a lot of time.

**Comment by thomas-tran** [comment]
@thehenrytsai  Thanks for the explanation. Where is the configuration to change batch writer waiting time in the node?

**Comment by thehenrytsai** [comment]
Assuming you are running against mainnet using the setup guide:

`mainnet-core-config.json` -> `batchingIntervalInSeconds`

**Comment by thomas-tran** [comment]
Thank you @thehenrytsai  @csuwildcat
