### ISSUE TITLE
Not supported BCoin API call in the getUnspentCoins function of the BitcoinProcessor class

### ISSUE THREAD

**Issue by jabdov** [decentralized-identity/ion#23]
The API call in the function `getUnspentCoins(address)` of the `BitcoinProcessor` class, used by the `writeTransaction(anchorFileHash)` function in the same class, to write the hash of the anchor file in the blockchain is not supported by the BCoin API. This causes an error when the ION node tries to write the hash of the anchor file to the blockchain (provided the wallet has enough funds) making DID creation operations fail.

This function calls a BCoin API GET method `/coin/address/${addressToSearch}` which is not supported by the BCoin API. I tried to look for the intended method but couldn't find it in the current API specification. The unspent coins could be obtained by processing all transactions associated with a particular address using the GET method `/tx/address/${addressToSearch}` or perhaps using the BCoin wallet APIs (instead of the node APIs).

I was not successful with any of these (someone shout if find a solution) and opted for an external service provided by `chain.so`. Not ideal for production, but could solve the problem for testing. I am happy to share the code I am using to make it work for now.

**Comment by jabdov** [comment]
> The API call in the function `getUnspentCoins(address)` of the `BitcoinProcessor` class, used by the `writeTransaction(anchorFileHash)` function in the same class, to write the hash of the anchor file in the blockchain is not supported by the BCoin API. This causes an error when the ION node tries to write the hash of the anchor file to the blockchain (provided the wallet has enough funds) making DID creation operations fail.
> 
> This function calls a BCoin API GET method `/coin/address/${addressToSearch}` which is not supported by the BCoin API. I tried to look for the intended method but couldn't find it in the current API specification. The unspent coins could be obtained by processing all transactions associated with a particular address using the GET method `/tx/address/${addressToSearch}` or perhaps using the BCoin wallet APIs (instead of the node APIs).
> 
> I was not successful with any of these (someone shout if find a solution) and opted for an external service provided by `chain.so`. Not ideal for production, but could solve the problem for testing. I am happy to share the code I am using to make it work for now.

I have managed to use the BCoin wallet API RPC call [listunspent](https://bcoin.io/api-docs/index.html?shell--cli#listunspent) succesfully in the function `getUnspentCoins(address)` of the `BitcoinProcessor` class. However, the rpcCall helper function must be rewritten as the URI for the BCoin wallet API is different from the URI for the BCoin node (e.g. localhost:18334 is the default BCoin wallet API for the bitcoin testnet). In addition, one must import the address in the wallet database and enable indexing for  addresses and transactions. The other solution without consuming an external API service is to generate the coins out of the list of transactions for the given address using the GET method `/tx/address/${addressToSearch}` of the BCoin node API. This requires building a helper function to get all coins from all the transactions.

**Comment by thehenrytsai** [comment]
Confirmed that this is a real regression. Considering just taking dependency directly against Bitcoin Core client. Meanwhile this was the Bcoin commit that was tested to be working before the breaking change occurred: af19d802f56e83243864af9d388596cdc3769564

**Comment by jabdov** [comment]
I have created this [pull ](https://github.com/decentralized-identity/sidetree/pull/240) in the [sidetree](https://github.com/decentralized-identity/sidetree) repo to fix this issue.

**Comment by thehenrytsai** [comment]
@jabdov, FYI, I've merged in your fix into Sidetree master branch, however upon testing, it does not appear to be working as an address with some balance is returned to have 0 coins by the print out:

`    console.info(`Returning ${unspentCoins.length} coins`);`

**Comment by jabdov** [comment]
@thehenrytsai , have you checked the API works using command line e.g. `curl localhost:18331/tx/address/$addresstoSearch` where `$addresstoSearch` is the bitcoin address you have some balance.
If it returns a list of transactions in JSON format then the provided fix should work (it is working with me and have tested several times).
If it returns nothing or gives an error message it is probably related to the fact you need to require BCoin to index your addresses and transactions. You can do that stopping the BCoin service, updating the BCoin configuration file (`bcoin.conf`) and adding the following couple of lines in it:
`index-address: true
index-tx: true`
Restart BCoin, wait until addresses and transactions have been indexed (it can take a while 10-20min depending on the machine).
Test the API endpoint above again. It should work now.
If the API works (i.e. returns the list of transactions), please send me the console.log output and will check why the fix I provided could fail.

**Comment by thehenrytsai** [comment]
Upgraded to Sidetree v0.3.0 in 8116696a3a62190facb1c75bc714fcbd4392fbff which removed dependency on BCoin. Official Bitcoin Core client can now be used instead.
