### ISSUE TITLE
Can run ION with local bitcoin network

### ISSUE THREAD

**Issue by KunPengRen** [decentralized-identity/ion#241]
Hi, I am a new guy to this project, I have doubts about can I run ION in a test way, run ION locally, and connect with a private bitcoin network?

**Comment by BenjaminMoe** [comment]
I've been spending some time getting Ion to run locally on a Raspberry Pi using Regtest. The documentation can be found here: https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-ion/docs/install-ion-dev.md

One loose end is that Ion seems to generate the address needed for the wallet randomly and haven't found a way to set a predictable value for that. The way I found what the wallet address was to run the Ion `bitcoin.js` file, try to write an operation, get the address from the error message and then add funds to the account via `bitcoin-core.cli` from the command line.

**Comment by csuwildcat** [comment]
> I've been spending some time getting Ion to run locally on a Raspberry Pi using Regtest. The documentation can be found here: https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-ion/docs/install-ion-dev.md
> 
> One loose end is that Ion seems to generate the address needed for the wallet randomly and haven't found a way to set a predictable value for that. The way I found what the wallet address was to run the Ion `bitcoin.js` file, try to write an operation, get the address from the error message and then add funds to the account via `bitcoin-core.cli` from the command line.
> 
> As far as running I have been able to create and resolve dids locally on my Pi 4 running Ubuntu 20.04.3 this way.

You should be able to set it in the config file: https://github.com/decentralized-identity/ion/blob/master/json/regtest-bitcoin-config.json#L8 (this is the testnet config, there's one for mainnet too)

**Comment by KunPengRen** [comment]
Thanks for above information, I will try on my local ubuntu machine, and response latter.

**Comment by KunPengRen** [comment]
> I've been spending some time getting Ion to run locally on a Raspberry Pi using Regtest. The documentation can be found here: https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-ion/docs/install-ion-dev.md
> 
> One loose end is that Ion seems to generate the address needed for the wallet randomly and haven't found a way to set a predictable value for that. The way I found what the wallet address was to run the Ion `bitcoin.js` file, try to write an operation, get the address from the error message and then add funds to the account via `bitcoin-core.cli` from the command line.
> 
> As far as running I have been able to create and resolve dids locally on my Pi 4 running Ubuntu 20.04.3 this way.

I try to install ion follow the document. when I creat a did, the console shows an error:
```
Event emitted: sidetree_batch_writer_loop_failure: {"code":"ipfs_failed_writing_content"}
```
Do you face this error or do you know how to fix the error?

**Comment by BenjaminMoe** [comment]
>Event emitted: sidetree_batch_writer_loop_failure: {"code":"ipfs_failed_writing_content"}

Looks like `ipfs` isn't running. What happens when you run

```
$ sudo systemctl status ipfs-daemon.service
```

One thing to mention is that the guide was written for Ubuntu on the Raspberry Pi 4. So if you're using a user that isn't named `ubuntu`, you'll need to update the service with your username for the systemd file. 

```
$ sudo vim /lib/systemd/system/ipfs-daemon.service
--- Create File ---
[Unit]
Description=IPFS daemon
Wants=network.target
After=network.target

[Service]
User=ubuntu <- change this
Group=ubuntu <- change this
Type=simple
Environment=IPFS_PATH=/home/ubuntu/snap/ipfs/common <- change this
ExecStart=/snap/bin/ipfs daemon --migrate
ExecStop=/usr/bin/pkill -f ipfs
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target
--- EOF ---
```

Another option is that you can start up another terminal and run `$ ipfs daemon` directly, and then start the ion-bitcoin and ion-core processes.

**Comment by KunPengRen** [comment]
Run successful on local ubuntu with the help of @BenjaminMoe document.
One issue of ipfs was solved by using desktop version ifps.
