### ISSUE TITLE
Broken link in the installation guide

### ISSUE THREAD

**Issue by rbinrais** [decentralized-identity/ion#25]
In section 2 [Setting up Bcoin](https://github.com/decentralized-identity/ion/blob/master/install-guide.md#2-setting-up-bcoin) of the [ION Installation Guide]( https://github.com/decentralized-identity/ion/blob/master/install-guide.md), link to the [automated script](https://github.com/decentralized-identity/sidetree/blob/master/lib/bitcoin/start.sh) is broken. I checked the [Sidetree](https://github.com/decentralized-identity/sidetree/tree/master/lib) repo and its [lib](https://github.com/decentralized-identity/sidetree/tree/master/lib) folder do not have Bcoin related files in it. 

Would recommend either update the link so it points to the correct script file or remove it.

**Comment by thehenrytsai** [comment]
Setup guide is updated in e08f7b30603316303b628774cec7803450aa13dd and the link is updated in 6104a92cd9a7e6220a77fc8db42a39ed5905ec37.
