### ISSUE TITLE
Retrieve a DID object using the DID URI and make an update operation

### ISSUE THREAD

**Issue by Ichigo85** [decentralized-identity/ion#289]
Hello,
I am really new to this project. I am trying to create a DID object in my local ION node, publish it and then make an update, to see if the new DID resolved returns the data I expect.
I noticed two things:

1. If I lose the DID object of the published DID, how can I retrieve it with its ION-tools functions? --- I solved it using ion-sdk, but I think it could be useful anyway ---
2. After making an update, waiting for it to be published successfully, if I fetch the DID, I can't find any new data.

I made an example of my code [here](https://codesandbox.io/s/did-test-77s6tm?file=/README.md)

What am I missing? The update transaction and operation are committed in mongoDb database and bitcoin node, but the resolved DID returns the 'first creation' did data.

[Same issue posted here](https://github.com/decentralized-identity/ion-tools/issues/35#issue-1388011820)

**Comment by marek5050** [comment]
+1 this would be nice - for some reason updating a ION DID is much more complicated once you lose the initial object.

**Comment by Ekiwoulf** [comment]
Hi,

+1, I can't update my ION DID. 
I am able to create and deactivate, but for some reason the update don't work. 

If someone can give help, that would be great.

**Comment by frankhinek** [comment]
@Ichigo85 @marek5050 @Ekiwoulf
The ION Tools [README](https://github.com/decentralized-identity/ion-tools) updated with complete working example of creating an updating an ION DID.

I also created an example repo that has detailed versions of create and update operations:
https://github.com/frankhinek/did-ion-examples

Let me know if this resolves the open questions. Thanks.

**Comment by Ichigo85** [comment]
Hello @frankhinek ! Thank you very much for your updated example. Closing the issue now :)
