### ISSUE TITLE
Create a milestone/roadmap document

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/ion#3]
Create a document that we can use to plan and describe the next phases of ION as we progress toward a public main net release.

**Comment by dbolser** [comment]
When do you expect a mainnet launch? 2 weeks? Or perhaps 2 years ;-P

**Comment by csuwildcat** [comment]
> When do you expect a mainnet launch? 2 weeks? Or perhaps 2 years ;-P

Just finished now - sorry, took a while: https://techcommunity.microsoft.com/t5/identity-standards-blog/ion-we-have-liftoff/ba-p/1441555

**Comment by dbolser** [comment]
Neeps, thanks for pushing it out :-)

I heard the news, but forgot this thread!
