### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by vongohren** [decentralized-identity/ion#32]
I just wonder, based on the installation guide.
Should not MacOS be supported?
Since all windows needs is node, and all linux needs is snapd.
Can MacOS run withtout snapd?

Bitcoin core runs on mac, mongoDB runs on mac.
And the latter parts are node dependent.

Is there something im missing that makes MacOS not able to run this?

**Comment by AlexITC** [comment]
You can install and run everything manually, from what I saw, there is nothing linux-specific besides some instructions.

**Comment by thehenrytsai** [comment]
@AlexITC is right, there is nothing technically Linux specific (or Windows specific for that matter). While we have not directly tested it on MacOS, it should work. Would love for someone to try it on MacOS and update install guide for it!

**Comment by vongohren** [comment]
Kk, I will not have time to try it out immediatly, but will close this and see what happens :)
