### ISSUE TITLE
Can you link to DIF, etc in the readme.md?

### ISSUE THREAD

**Issue by dbolser** [decentralized-identity/ion#33]
There are a few 'partner organisations' involved in the project like DIF. Can you add a section on 'Partner Organisations' (or similar) to the readme.md and link to DIF, etc.?

I can do this if you like.

**Comment by dbolser** [comment]
https://github.com/decentralized-identity/ion/pull/34

**Comment by thehenrytsai** [comment]
Thanks Dan for 2f9937cbcd5c404432f64a12293caedbf8cb8b2b.
