### ISSUE TITLE
Error when launching ION bitcoin service - missing instructions or FAQ?

### ISSUE THREAD

**Issue by adambarlow** [decentralized-identity/ion#46]
I have now Built ION successfully. Thanks @thehenrytsai for the update which fixes the build error. Now I am hitting a 'Transaction collection already exists.' error. I dug into the source but I didn't find this in the pre-built src, and then I searched in the dist\bitcoin.js and didn't find this string there either. Perhaps it's a bitcoind string.

My guess is that I need to configure a bitcoin wallet with bitcoin core first or generate my private key in a different way than I am doing.

There may be a section of the installation guide missing on this subject. Do you generate an address from bitcoin core or do you import an address that is generated in another way? I tried both.

Error message is below, help appreciated.

----------------------------------------------------------
Transaction collection already exists.
Checking if bitcoin contains a wallet for [SNIP -for habits sake]
Checking if bitcoin wallet for [SNIP-for habits sake] exists
Sending jRPC request id: 62kefvvcqrp
Error: Fetch failed [401]:
    at BitcoinProcessor.<anonymous> (/home/gitbit/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:543:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/gitbit/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Sidetree-Bitcoin node initialization failed with error: Error: Fetch failed [401]:

**Comment by adambarlow** [comment]
@thehenrytsai @csuwildcat 
I have verified that I can post to bitcoin RPC via curl. Is the 'bitcoinWalletImportString' that you place in the bitcoin-config.json file a private key of an address that exists in your testnet wallet? For example to get mine I called getnewaddress and then dumpprivekey, populating the config file with this private key.

Is that what I should be doing?

**Comment by thehenrytsai** [comment]
Hi @adambarlow, bitcoin wallet private key should only be used when you are writing transactions which I don't think is the issue in your case. Not all RPC calls require authentication so I still think it is authentication failure (based on the `401` code shown in your output), can you sanity perform the RPC call below and tell me what the output is (I suspect it will give you a `401`).

```
{
    "method": "getblockcount"
}
```

**Comment by adambarlow** [comment]
You are asking that I make that call via curl? It does return the correct blockheight, e.g.:

I did curl --user bitcoinrpc --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblockcount", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
Enter host password for user 'bitcoinrpc':

And I got.
{"result":1608360,"error":null,"id":"curltest"}

**Comment by thehenrytsai** [comment]
The response that you got is definitely right. Just for sanity, did you update the following properties in the `bitcoin-config` file to match your bitcoin core client settings?

```
  "bitcoinRpcUsername": "YOUR_USERNAME",
  "bitcoinRpcPassword": "YOUR_PASSWORD",
```

Make sure you `npm run build` after updating the config.

**Comment by adambarlow** [comment]
Yes, I am sure that these are correct. Pasting the full output. Seems like an issue with the wallet import string maybe?

Initializing ITransactionStore
Sidetree bitcoin service configuration:
{ bitcoinPeerUri: 'http://127.0.0.1:8332',
  bitcoinRpcUsername: 'bugs4bits7236$',
  bitcoinRpcPassword: 'bitcoinrpc',
  bitcoinWalletImportString: 'cSp7pj8Mk3z5LP19Dfg8RXBURvsdHQfD76BfEqPPqfwRrqFQPuCf',
  bitcoinFee: 4000,
  sidetreeTransactionPrefix: 'ion:',
  genesisBlockNumber: 1500000,
  databaseName: 'sidetree-bitcoin',
  transactionFetchPageSize: 100,
  mongoDbConnectionString: 'mongodb://localhost:27017/',
  port: 3002 }
(node:61775) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Transaction collection already exists.
Checking if bitcoin contains a wallet for n4XoyBf4UcetV7dEXK3se6fQ5dLQMYVNqG
Checking if bitcoin wallet for n4XoyBf4UcetV7dEXK3se6fQ5dLQMYVNqG exists
Sending jRPC request id: 3uaamqmmfe2
Error: Fetch failed [401]:
    at BitcoinProcessor.<anonymous> (/home/gitbit/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:543:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/gitbit/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Sidetree-Bitcoin node initialization failed with error: Error: Fetch failed [401]:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ion@0.5.0 bitcoin: `node dist/src/bitcoin.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ion@0.5.0 bitcoin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitbit/.npm/_logs/2019-11-15T01_46_07_836Z-debug.log

**Comment by thehenrytsai** [comment]
In your last dump is shows:

```
bitcoinRpcUsername: 'bugs4bits7236$',
bitcoinRpcPassword: 'bitcoinrpc',
```

but in your previous CURL output, it suggests that `bitcoinrpc` is the username not password, are you sure you haven't got them switched?

**Comment by adambarlow** [comment]
🤦‍♂️👌 thanks for the catch. Always good to have a second set of eyes. Whoops!

**Comment by adambarlow** [comment]
I then got the following error, that I have since resolved:

Sending jRPC request id: 4n1d5cqu84h
Configuring bitcoin peer to watch address n4XoyBf4UcetV7dEXK3se6fQ5dLQMYVNqG. This can take up to 10 minutes.
Sending jRPC request id: 5hl1u1rni29
Error: Fetch failed [500]: {"result":null,"error":{"code":-4,"message":"The wallet already contains the private key for this address or script"},"id":"5hl1u1rni29"}

Referring to my previous question above, this seems to hint that I should be creating a private key that is not inside the default wallet for my bitcoind instance and then ION will either sweep or import it. I assume at this point I should send funds to the public address that matches my private key.

It would be good to add these details to the installation instructions. Once I figure out the correct steps I'll submit a PR with some suggested updates to the instructions.

**Comment by thehenrytsai** [comment]
There maybe a bug where the code made some incorrect assumptions about the existence of the private key in the bitcoin core client. Would be great if you could a file separate issue in the `sidetree` repo if you a repro.

Regarding the time out, in your log:

```
Sidetree-Bitcoin node initialization failed with error: FetchError: network timeout at: http://127.0.0.1:8332/
```

The port `8332` is typically used for mainnet, not testnet, are you sure the port is not supposed to be `18332` instead?

**Comment by adambarlow** [comment]
Yes, I've switched bitcoind back to 18332, I had changed it when the previous authentication issues were happening. I don't think that was the issue as it's working now the same as before. It syncs for a while and then occasionally hits a delay which causes retries and then a timeout. But at least on the last two runs it started more or less where it left off and I it is now almost to the current testnet block height 🤞

**Comment by adambarlow** [comment]
This issue description is vague. I'll open a new issue for the more specific issues I've found here

**Comment by LiranCohen** [comment]
I know this issue is closed, but I'm getting the same issue getting stuck at exactly block 1510624 and timing out each time.  Has anyone else encountered this? @adambarlow were you able to get past this issue?

**Comment by adambarlow** [comment]
@LiranCohen, yes, I did get this working eventually. I believe I had to keep restarting it over and over, my suspicion is that there is race condition somewhere, but I can't be sure.

**Comment by LiranCohen** [comment]
Hrm, I will have to dig into this a little more when I have time. It's strange that it keeps having the issue on the same exact block height.

Also as a side note, I am trying to run this on under-powered hardware (Raspberry Pi 4 4GB).  I'm monitoring memory and CPU usage though and all looks good.

**Comment by adambarlow** [comment]
Do you have a swap enabled? I think I vaguely remember running out of memory and then adding a swapfile.

**Comment by LiranCohen** [comment]
Let me give that a try.

**Comment by LiranCohen** [comment]
No dice, keeps dying at the same block height.  Once you got past that initial issue you've been smooth sailing since? Any issues starting back up?

**Comment by LiranCohen** [comment]
Another Update:

Added the "requestMaxRetries" property to the bitcoin config file and updated it to 10 retries (default is 3).

So far the client was able to get the requested block after 4 retries. Let's see if this works.
