### ISSUE TITLE
Accessing Sidetrees REST API endpoints on ION instance

### ISSUE THREAD

**Issue by simbro** [decentralized-identity/ion#49]
I have installed an ION instance on a Linux server, and it seems to be running smoothly, and I am able to successfully resolve the test did from the installation guide.

However, any other API endpoint I try to access, as described in the [Sidetrees implementation document](https://github.com/decentralized-identity/sidetree/blob/master/docs/implementation.md#blockchain-rest-api), is interpreted as a DID resolution request (the log files just show: "Handling resolution request for: transactions..."

I've tried GET /time, GET /transactions and /POST transactions, but each time I simply getting an empty "400 Bad Request" response.

**Comment by thehenrytsai** [comment]
Hi @simbro, I suspect that you are invoking the bitcoin microservice APIs (such as `GET /time`) against the core service endpoint, which would definitely not work. Make sure you are hitting the bitcoin microservice endpoint for those example API requests you gave.

**Comment by simbro** [comment]
Thanks @thehenrytsai - that's exactly the problem.  It's obvious now that I look at the config files in the json folder.  The core, bitcoin and ipfs services are running on ports 3000, 3002, and 3003 respectively and each service exposes it's own endpoints.  Thanks for your help!
