### ISSUE TITLE
Is it possible to get the DID of each operation in the batch file?

### ISSUE THREAD

**Issue by simbro** [decentralized-identity/ion#64]
I'm trying to use the REST API endpoints to observe sidetree transactions on ION, but the operations don't seem to contain any reference to the DIDs they pertain to.  Is there a way to dereference the DIDs of each operation?

(I'm using ION version 0.5.0)

This is what I'm doing so far:

GET http://ion-instance:3002/transactions

this gets a list of transactions, which all look like this:

```
[{
  "transactionNumber":6490271109873672,
  "transactionTime":1511134,
  "transactionTimeHash":"0000000000000ef8f824192e0f7b5d2ad525bab1f322fa5081e80e7481c8b96e",
  "anchorString":"EiAy4Y72hlK7laJfnkAsCKw6azkiICcOE2Df3QF4cxSlKw"
}]
```

For each of these transactions, I take the `anchorString` value, and use it to make a request like this:

GET http://ion-instance:3003/EiAmQ0AVj3ixs3jK-25yWEgcsaS3q47sPD_EEguzIn8S7Q?max-size=2000

Which gives me a JSON object that looks like this:

```
{"batchFileHash":"EiBtjyhK_Z2cszuSqUhmCSK1t17iTvtmydxaMZKdxsBo8A","merkleRoot":"UH2qCm60I9mniBHVcdeUkVd1OmPF8P2rnBM93dGU0AQ"}
```

I then take the `batchFileHash` value, and use it to make the same request again, e.g.

GET http://ion-instance:3003/EiBtjyhK_Z2cszuSqUhmCSK1t17iTvtmydxaMZKdxsBo8A?max-size=2000

Which gives me an object like this:

```
{
  "operations": [
    "eyJoZWFkZXIiOnsiYWxnIjoiRVMyNTZLIiwia2lkIjoiI2tleTEiLCJvcGVyY.....",
    "eyJoZWFkZXIiOnsiYWxnIjoiRVMyNTZLIiwia2lkIjoiI2tleTEiLCJvcGVyY....."
  ]
}
```
I take each operation and run it through a base64decode operation which gives me something like this:

```
{
  "header": {
    "alg": "ES256K",
    "kid": "#key1",
    "operation": "create",
    "proofOfWork": "{}"
  },
  "payload": "eyJjcmVhdGVkIjoiMjAxOS0wNC0yM1QxNzoyMzow....",
  "signature": "MEUCIHPTgpJ7K8SLsGxBM05Rti9MMJnxgbdwllGZ9XhxD1QV...."
}
```

I take the payload value and run it through another base64decode operation, which gives me something like this:

```
{
  "created": "2019-04-23T17:23:06.754Z",
  "@context": "https://w3id.org/did/v1",
  "publicKey": [
    {
      "id": "#key1",
      "type": "Secp256k1VerificationKey2018",
      "publicKeyJwk": {
	"kty": "EC",
	"crv": "P-256K",
	"key_ops": ["sign", "verify"],
	"x": "5XuyCgM-ZvnR7XxJtXhUMXrzIen4W6kuGFHiVPeEWSQ",
	"y": "-RaqLq1AX_aRbxJwrx-mhcPffNMD7qNlEfe5-y0xH-o",
	"d": "dX0aOwt1lBZ0NIxQ-EyHhYOOgwD6-MZMMeQw3RBKhh8",
	"kid": "#key1"
      }
    }
  ]
}
```

However, I can't seem to figure out how to ascertain the DID this operation relates to.

**Comment by simbro** [comment]
I did a bit more testing on this today, and it seems that older transactions have a different format to the anchorFile, that is, they contain an `didUniqueSuffixes` property:

```
{
    "batchFileHash": "EiAWU0PAu-anVbqXrGLoU3Gd26KPRx70YFd6wV-lnpfSuw",
    "merkleRoot": "CN8pvEAsD35vYxh2y-x4FXIvjoboGKpo401YxGbWvYE",
    "didUniqueSuffixes": [
      "EiBR8vuOtZrHqf_reS7GENZF_ertBlozTC-gXAHrTieNOA",
      "EiC7LUJu6IWvpp1_RGIsTMUXlMj21yhK9bWPKZ-r8S54MQ"
    ]
  }
```

That would answer my initial question, in as far as, it would explain how to resolve the DIDs relating to the operations in the batch file.

However...

The batch files for those older transactions, (any transaction with the "didUniqueSuffixes" property) seem to be missing.  I'm just getting a 404 when trying to request them from the CAS endpoint.

Why are those batch files missing?  Is it just down to anomalies of a the test network? Perhaps the batch files were not cached or pinned anywhere and the originals have gone?

Also, and more importantly, **how can there be sidetree transactions with no didUniqueSuffixes - surely this is incorrect?**

**Comment by Dinglebarry9** [comment]
By any chance are you able to create DID's?

**Comment by simbro** [comment]
Good question, I just tried to create a DID and it seemed to work fine.  But I wasn't able to resolve the DID after creating it.  The snippets below contains the request I sent to the ION node to create the DID, and the response back from the node.

REQUEST
```
  {
    "payload": "eyJAY29udGV4dCI6Imh0dHBzOi8vdzNpZC5vcmcvZGlkL3YxIiwicHVibGljS2V5IjpbeyJpZCI6IiNrZXktMSIsInR5cGUiOiJTZWNwMjU2azFWZXJpZmljYXRpb25LZXkyMDE4IiwicHVibGljS2V5SndrIjp7Imt0eSI6IkVDIiwia2lkIjoiI2tleS0xIiwiY3J2IjoiUC0yNTZLIiwieCI6ImZUSFNvdDJSc3VZQUx4dUUzZFVhNFRuQWlVWG1RZ1JWV2pHckM1b2lOWmciLCJ5IjoiLTdWNW85Z3R4a0xMekdzN1hicHEwOVJaLU5rQlhDWkNJM2EtTEdtaGhFcyIsInVzZSI6InZlcmlmeSIsImRlZmF1bHRFbmNyeXB0aW9uQWxnb3JpdGhtIjoibm9uZSIsImRlZmF1bHRTaWduQWxnb3JpdGhtIjoiRVMyNTZLIn0sInVzYWdlIjoic2lnbmluZyJ9LHsiaWQiOiIja2V5LTEiLCJ0eXBlIjoiU2VjcDI1NmsxVmVyaWZpY2F0aW9uS2V5MjAxOCIsInB1YmxpY0tleUp3ayI6eyJrdHkiOiJFQyIsImtpZCI6IiNrZXktMSIsImNydiI6IlAtMjU2SyIsIngiOiJXb0xWUnBLUzJvNzJKVjRjc0MwYXE1c1RtbkZiUVdfcHBlaWhPeXZGTXRVIiwieSI6Inh6ajRrd0JmRnFKb19yQkpneU40QUhheHowWDRDYjFtb3hZQVNOeXNxWlkiLCJ1c2UiOiJ2ZXJpZnkiLCJkZWZhdWx0RW5jcnlwdGlvbkFsZ29yaXRobSI6Im5vbmUiLCJkZWZhdWx0U2lnbkFsZ29yaXRobSI6IkVTMjU2SyJ9LCJ1c2FnZSI6InJlY292ZXJ5In1dLCJzZXJ2aWNlIjpbeyJpZCI6IklkZW50aXR5SHViIiwidHlwZSI6IklkZW50aXR5SHViIiwic2VydmljZUVuZHBvaW50Ijp7IkBjb250ZXh0Ijoic2NoZW1hLmlkZW50aXR5LmZvdW5kYXRpb24vaHViIiwiQHR5cGUiOiJVc2VyU2VydmljZUVuZHBvaW50IiwiaW5zdGFuY2UiOlsiZGlkOnRlc3Q6aHViLmlkIl19fV19",
    "signature": "MEYCIQDORQRZl2anyGhZGBuN-pREMY9_caAoPjsQFcXaKKYCPgIhAP7AYfbVtH21KScDWH5tTNqbLq2reKN0YpcUmb80pphr",
    "protected": "eyJhbGciOiJFUzI1NksiLCJraWQiOiIja2V5LTEiLCJvcGVyYXRpb24iOiJjcmVhdGUiLCJwcm9vZk9mV29yayI6Int9In0"
  }
```

RESPONSE:
```
  {
    "@context": "https://w3id.org/did/v1",
    "publicKey": [
      {
        "id": "#key-1",
        "type": "Secp256k1VerificationKey2018",
        "publicKeyJwk": {
          "kty": "EC",
          "kid": "#key-1",
          "crv": "P-256K",
          "x": "fTHSot2RsuYALxuE3dUa4TnAiUXmQgRVWjGrC5oiNZg",
          "y": "-7V5o9gtxkLLzGs7Xbpq09RZ-NkBXCZCI3a-LGmhhEs",
          "use": "verify",
          "defaultEncryptionAlgorithm": "none",
          "defaultSignAlgorithm": "ES256K"
        },
        "usage": "signing"
      },
      {
        "id": "#key-1",
        "type": "Secp256k1VerificationKey2018",
        "publicKeyJwk": {
          "kty": "EC",
          "kid": "#key-1",
          "crv": "P-256K",
          "x": "WoLVRpKS2o72JV4csC0aq5sTmnFbQW_ppeihOyvFMtU",
          "y": "xzj4kwBfFqJo_rBJgyN4AHaxz0X4Cb1moxYASNysqZY",
          "use": "verify",
          "defaultEncryptionAlgorithm": "none",
          "defaultSignAlgorithm": "ES256K"
        },
        "usage": "recovery"
      }
    ],
    "service": [
      {
        "id": "IdentityHub",
        "type": "IdentityHub",
        "serviceEndpoint": {
          "@context": "schema.identity.foundation/hub",
          "@type": "UserServiceEndpoint",
          "instance": ["did:test:hub.id"]
        }
      }
    ],
    "id": "did:ion:test:EiBe8EVPeO87uExfvBlqQgZkuyour3GKL_XmjeVPBho8uw"
  }
```

Then when I try to resolve the above DID, I get the following error:

GET http://ion-instance:3001/did:ion:test:EiBe8EVPeO87uExfvBlqQgZkuyour3GKL_XmjeVPBho8uw

returns a "404 Not Found"

What's even stranger is that when I take the hash of the batch file from the logs and try to retrieve it from the CAS endpoint, it comes back as binary ?!?!  I've seen this with batch files from other arbitrary transactions on the network as well.

**Comment by Dinglebarry9** [comment]
I have been trying to even get that far for a while now, but always get a bad request. I followed the example on https://didproject.azurewebsites.net/docs/overview.html but I think it is out of date. I have the ion node up and running but I am stuck with the create part. Maybe If you have some time we can collaborate on a create walkthrough PR.

**Comment by Dinglebarry9** [comment]
This is the js I am using to make the JWT
```
async function makeJws() {

    // construct the JWS payload
    const body = {
        "@context": "https://w3id.org/did/v1",
        publicKey: [
            {
                id: jwkPub.kid,
                type: "Secp256k1VerificationKey2018",
                publicKeyJwk: jwkPub,
                "usage": "signing"
            },
            {
                id: jwkPubRecover.kid,
                type: "Secp256k1VerificationKey2018",
                publicKeyJwk: jwkPubRecover,
                "usage": "recovery"
            }
        ],
        service: [
            {
                id: "IdentityHub",
                type: "IdentityHub",
                serviceEndpoint: {
                    "@context": "schema.identity.foundation/hub",
                    "@type": "UserServiceEndpoint",
                    instance: [
                        "did:test:hub.id",
                    ]
                }
            }
        ],
    };

    // Construct the JWS header
    const header = {
        alg: jwkPub.defaultSignAlgorithm,
        kid: jwkPub.kid,
        //operation:'create',
        //proofOfWork:'{}'
    };

    // Sign the JWS
    const cryptoFactory = new didAuth.CryptoFactory([new didAuth.Secp256k1CryptoSuite()]);
    const jwsToken = new didAuth.JwsToken(body, cryptoFactory);
    const signedBody = await jwsToken.signAsFlattenedJson(privateKey, {header}.Protect);
    //const signedBody = await jwsToken.Protect.sign(privateKey, {header});

    // Print out the resulting JWS to the console in JSON format
    console.log(JSON.stringify(signedBody));

}
```

**Comment by fabianekc** [comment]
I'm also struggling to create a DID using the information on the Sidetree Protocol Specification. So far I have documented my steps here: [https://github.com/OwnYourData/did-ion](https://github.com/OwnYourData/did-ion)    
Would love to join a collaboration to create a walkthrough!

**Comment by Dinglebarry9** [comment]
@fabianekc, Yes totally I will pull your repo and add some stuff.

**Comment by simbro** [comment]
Seeing as this issue was originally opened with regards to missing DIDs in the anchor files, I'm going to close it for now, and I will try to resolve the issue offline.  I'm happy to help with the issue of creating a DID using ION, and to contribute to some documentation, but lets do it under @fabianekc 's project for now.

**Comment by Dinglebarry9** [comment]
@simbro one question, what is `"did:test:hub.id"`, do you host it yourself or is it somewhere else, I don't know where to start, all the decentralized-identity repos that concern identity hubs are depreciated.
