### ISSUE TITLE
Api Documentation for DID related operations

### ISSUE THREAD

**Issue by SethiShivam** [decentralized-identity/ion#84]
Hi Team,

Is there any documentation where i can find all the apis for testing did operations and service hubs.

Actually i remember that i had used it before .but now it got disappared .Could you please help me with that . I want to do some testing and want to study more about microsoft ION 

Best Regards
Sethi Shivam

**Comment by thehenrytsai** [comment]
Hi Sethi,

A couple spec to start:

[API Spec](https://identity.foundation/sidetree/api/)
[Sidetree Spec](https://identity.foundation/sidetree/spec/)

**Comment by csuwildcat** [comment]
Documented above, with a lib that makes it easy here: https://www.npmjs.com/package/@decentralized-identity/ion-tools
