### ISSUE TITLE
DID resolution check fails after following installation guide

### ISSUE THREAD

**Issue by frankhinek** [decentralized-identity/ion#85]
After following the [ION Installation Guide](https://github.com/decentralized-identity/ion/blob/master/install-guide.md), I am unable to successfully complete the last step in the guide:

> Verify ION is running properly by checking the following DID resolution link in your browser: http://localhost:3000/did:ion:test:EiDk2RpPVuC4wNANUTn_4YXJczjzi10zLG1XE4AjkcGOLA

There is no result returned by the curl command:

```bash
$ curl http://localhost:3000/did:ion:test:EiDk2RpPVuC4wNANUTn_4YXJczjzi10zLG1XE4AjkcGOLA
```

The `ion-core` process (i.e., `npm run core`) log entries immediately after executing the `curl` are:

```bash
Refreshing cached blockchain time...
Refreshed blockchain time: {"time":1746649,"hash":"0000000063a4ab5a56c92a61e716d954b7440d51dcf61e5e21a51f630c5ca884"}
Handling resolution request for: did:ion:test:EiDk2RpPVuC4wNANUTn_4YXJczjzi10zLG1XE4AjkcGOLA...
Resolving DID unique suffix 'EiDk2RpPVuC4wNANUTn_4YXJczjzi10zLG1XE4AjkcGOLA'...
Fetching Sidetree transactions from blockchain service...
Fetching URI 'http://127.0.0.1:3002/transactions?since=7498991423979525&transaction-time-hash=0000000000000670b5aba7c546cb349380d22cf648385f885af8db876db72418'...
Fetch response: 200'.
Fetched 0 Sidetree transactions from blockchain service in 59 ms.
Successfully kicked off downloading/processing of all new Sidetree transactions.
Fetched 0 unresolvable transactions to retry in 1 ms.
Waiting for 60 seconds before fetching and processing transactions again.
```

## Configuration Files

<details>
<summary><b>~/.bitcoin/bitcoin.conf</b></summary>

```yaml
testnet=1
server=1
datadir=/home/<username>/.bitcoin
rpcuser=[RPC-USERNAME]
rpcpassword=[RPC-PASSWORD]
txindex=1
```

</details>

<details>
<summary><b>json/bitcoin-config.json</b></summary>

```json
{
  "bitcoinFeeSpendingCutoffPeriodInBlocks": 1,
  "bitcoinFeeSpendingCutoff": 0.01,
  "bitcoinPeerUri": "http://localhost:18332",
  "bitcoinRpcUsername": "[RPC-USERNAME]",
  "bitcoinRpcPassword": "[RPC-PASSWORD]",
  "bitcoinWalletOrImportString": "[WALLET-PRIVATE-KEY]",
  "sidetreeTransactionFeeMarkupPercentage": 5,
  "sidetreeTransactionPrefix": "ion:test:",
  "genesisBlockNumber": 1723000,
  "databaseName": "sidetree-bitcoin",
  "transactionFetchPageSize": 100,
  "mongoDbConnectionString": "mongodb://localhost:27017/",
  "port": 3002,
  "valueTimeLockAmountInBitcoins": 0
}
```

_Note_: Where `[WALLET-PRIVATE-KEY]` is the output of `bitcoin-cli dumpprivkey <wallet_public_key>` and `<wallet_public_key>` was created by executing `bitcoin-cli getnewaddress ""`
</details>

<details>
<summary><b>json/core-config.json</b></summary>

```json
{
  "batchingIntervalInSeconds": 600,
  "blockchainServiceUri": "http://127.0.0.1:3002",
  "contentAddressableStoreServiceUri": "http://127.0.0.1:3003",
  "didMethodName": "ion:test",
  "maxConcurrentDownloads": 20,
  "mongoDbConnectionString": "mongodb://localhost:27017/",
  "observingIntervalInSeconds": 60,
  "port": 3000
}
```

</details>

Since it appears both ways in ION guides/docs, I have tried with both of the following configurations for `bitcoin-config.json` and execute `npm run build` each time:

```json
  "sidetreeTransactionPrefix": "ion:",
```
or
```json
  "sidetreeTransactionPrefix": "ion:test:",
```

## Version Information

Ubuntu 18.04 LTS
7.5 GB RAM
1TB SSD
Direct Internet connection with ports open: tcp/4002, tcp/4003, tcp/18333

```bash
$ node -v
v10.20.1
```
```bash
$ bitcoind --version
Bitcoin Core version v0.19.1
```
```bash
$ curl http://localhost:3002/version
{"name":"bitcoin","version":"0.7.0"}
```
```bash
$ curl http://localhost:3003/version
{"name":"ipfs","version":"0.7.0"}
```

## Additional Information

The first time I execute `npm run core` the logging output repeatedly displays what appears to be several errors when fetching `EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A`, but this may be a misinterpretation given that I'm new to ION.  The suspect lines are:

* `Fetched 0 Sidetree transactions from blockchain service in 67 ms.`
* `Fetched 1 unresolvable transactions to retry in 2 ms.`
* `Recording failed processing attempt for transaction '7498991423979525'...`

and here's the full log:

```bash
$ npm run core
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/2638/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> ion@0.6.0 core /home/fh185036_ncr_com/ion
> node dist/src/core.js

(node:25315) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Transaction collection already exists.
Unresolvable transaction collection already exists.
Refreshing cached blockchain time...
Refreshed blockchain time: {"time":1746649,"hash":"0000000063a4ab5a56c92a61e716d954b7440d51dcf61e5e21a51f630c5ca884"}
Starting periodic transactions processing.
Sidetree node running on port: 3000
Start operation batch writing...
Fetching Sidetree transactions from blockchain service...
Fetching URI 'http://127.0.0.1:3002/transactions?since=7498991423979525&transaction-time-hash=0000000000000670b5aba7c546cb349380d22cf648385f885af8db876db72418'...
Batch size = 0
End batch writing. Duration: 16 ms.
Waiting for 600 seconds before writing another batch.
Fetch response: 200'.
Fetched 0 Sidetree transactions from blockchain service in 59 ms.
Successfully kicked off downloading/processing of all new Sidetree transactions.
Fetched 1 unresolvable transactions to retry in 2 ms.
Downloading anchor file 'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A', max file size limit 1000000 bytes...
Downloading file 'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A', max size limit 1000000...
Finished processing transaction '7498991423979525'.
Recording failed processing attempt for transaction '7498991423979525'...
Record transaction 7498991423979525 with anchor string AQAAAA.EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A to retry after 3840 seconds.
Waiting for 60 seconds before fetching and processing transactions again.
Refreshing cached blockchain time...
Refreshed blockchain time: {"time":1746649,"hash":"0000000063a4ab5a56c92a61e716d954b7440d51dcf61e5e21a51f630c5ca884"}
Fetching Sidetree transactions from blockchain service...
Fetching URI 'http://127.0.0.1:3002/transactions?since=7498991423979525&transaction-time-hash=0000000000000670b5aba7c546cb349380d22cf648385f885af8db876db72418'...
Fetch response: 200'.
Fetched 0 Sidetree transactions from blockchain service in 67 ms.
Successfully kicked off downloading/processing of all new Sidetree transactions.
Fetched 1 unresolvable transactions to retry in 2 ms.
Downloading anchor file 'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A', max file size limit 1000000 bytes...
Downloading file 'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A', max size limit 1000000...
Finished processing transaction '7498991423979525'.
Recording failed processing attempt for transaction '7498991423979525'...
Record transaction 7498991423979525 with anchor string AQAAAA.EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A to retry after 7680 seconds.
Waiting for 60 seconds before fetching and processing transactions again.
```

While this is occurring, the `npm run ipfs` log repeatedly prints out:

```bash
Handling fetch request for 'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A'...
'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A' not found on IPFS.
Handling fetch request for 'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A'...
'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A' not found on IPFS.
Handling fetch request for 'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A'...
'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A' not found on IPFS.
Handling fetch request for 'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A'...
'EiAHFzYUV8yKtedkr1eXsY7tysqgNTKpTPrc-kxaVSfF3A' not found on IPFS.
```

**Comment by thehenrytsai** [comment]
Hi @frankhinek for trying setting up an IONnode. The `sidetreeTransactionPrefix` is `ion:` regardless of the network used, that is the prefix used for the anchor string.

The DID for testing at in document is out dated because we have since updated the genesis block, and we have updated the test DID in the `dev` branch.

Could you please try `did:ion:test:EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA`?

As a side note, we will merge in changes from `dev` branch to `master` in the coming days, but feel free to checkout the `dev` branch directly because it does have a few critical bug fixes.

**Comment by frankhinek** [comment]
Hi @thehenrytsai -- thanks for the quick response.

I rebuilt the bitcoin/ION/sidetree/ipfs node from scratch using the `dev` branch.

When I run `curl http://localhost:3000/did:ion:test:EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA` no output is returned.  When I run in verbose mode, the response is an HTTP Error 400:

```bash
curl http://localhost:3000/did:ion:test:EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA --verbose
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /did:ion:test:EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Type: application/octet-stream
< Content-Length: 0
< Date: Thu, 28 May 2020 16:12:28 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
```

Nothing is reported in any of the runnings logs I have from `npm run bitcoin`, `npm run ipfs`, or `npm run core`.

Just to confirm the `bitcoinWalletImportString` value in `json/testnet-bitcoin-config.json` is the private key from my Bitcoin node, correct? (i.e., output of `bitcoin-cli dumpprivkey <public_key>`)

**Comment by frankhinek** [comment]
It does appear the node is running and responding to requests because `curl http://localhost:3000/version --verbose` returns

```bash
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /version HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 106
< Date: Thu, 28 May 2020 18:21:54 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
[{"name":"core","version":"0.7.0"},{"name":"bitcoin","version":"0.7.0"},{"name":"ipfs","version":"0.7.0"}]
```

**Comment by thehenrytsai** [comment]
Sorry, for the late response this time.

We have recently update the URL to be more "RESTful" but forgot to update the guide. So it needs to be:

http://localhost:3000/identifiers/did:ion:test:EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA

Hopefully that'll resolve for you this time!

Note that we are about to release the next version in the next couple of days which will be a hard fork that requires you to wipe your MongoDB.

**Comment by frankhinek** [comment]
Hi @thehenrytsai -- no worries.  Thanks for the follow up.

Since the routes were changed, that explains the 400 response code.

I tested again just now:

`curl http://localhost:3000/identifiers/did:ion:test:EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA`

continues to return no response.  In verbose mode (`curl ... -v`) the full response is:

```bash
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /identifiers/did:ion:test:EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: application/octet-stream
< Content-Length: 0
< Date: Thu, 04 Jun 2020 14:29:36 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
```

Here is the log output from ion-core:

```bash
Handling resolution request for: did:ion:test:EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA...
Resolving DID unique suffix 'EiDu6ZLMupgrqTQJjOki6xGEQZ9iUslA5ro_LzMXEXEoCA'...
```

**Comment by thehenrytsai** [comment]
Hi @frankhinek,

Glad we got pass the routing issue. One thing at a time! = ]

Looking at the IPFS service log now, do you see some successful/unsuccessful fetching activity?

```

**Comment by frankhinek** [comment]
Yes, as soon as all three microservices are running (ion-core, ion-ipfs, ion-bitcoin), I begin to see the following 5 IPFS log entries repeated:

```bash
Handling fetch request for 'EiAbGXIUOqjZK0CMrOwB5WYG0yLLyqvQ9U6Wqs7Br9qDmA'...
Handling fetch request for 'EiAbGXIUOqjZK0CMrOwB5WYG0yLLyqvQ9U6Wqs7Br9qDmA'...
Handling fetch request for 'EiALgqE_O3HKsFzJOdx9u1bXolW8hNtF9uJ7kBIzbaCqmA'...
Handling fetch request for 'EiBX4Se0ufCMaGvXHDVhwWj0AcMMygtlsKxD3mRoD-TS6w'...
Handling fetch request for 'EiD1IAVYSl6D5UIYmZ6poPc3I-LupV_hpDs1pt5fO2naUA'...
Handling fetch request for 'EiD1IAVYSl6D5UIYmZ6poPc3I-LupV_hpDs1pt5fO2naUA'...
'EiAbGXIUOqjZK0CMrOwB5WYG0yLLyqvQ9U6Wqs7Br9qDmA' not found on IPFS.
'EiAbGXIUOqjZK0CMrOwB5WYG0yLLyqvQ9U6Wqs7Br9qDmA' not found on IPFS.
'EiALgqE_O3HKsFzJOdx9u1bXolW8hNtF9uJ7kBIzbaCqmA' not found on IPFS.
'EiBX4Se0ufCMaGvXHDVhwWj0AcMMygtlsKxD3mRoD-TS6w' not found on IPFS.
'EiD1IAVYSl6D5UIYmZ6poPc3I-LupV_hpDs1pt5fO2naUA' not found on IPFS.
'EiD1IAVYSl6D5UIYmZ6poPc3I-LupV_hpDs1pt5fO2naUA' not found on IPFS.
```

Can you point me to docs/steps to create and store ION files so that I can verify my local setup is working?

I found an example here: https://github.com/ownyourdata/did-ion

but given all of the rapid changes, it seems like none of the docs/guides are up to date.

**Comment by thehenrytsai** [comment]
The API and Sidetree spec located here are always kept up to date:

[API Spec](https://identity.foundation/sidetree/api/)
[Sidetree Spec](https://identity.foundation/sidetree/spec/)

In fact ION v0.8.0 aligns with the specification there.

But it is probably too low level as far an admin is concerned. Try this:

```
git checkout master
```

Install CLI (work in progres):
```
git install -g .
```

Generate a create operation:
```
ion operation create
```

This should generate a create operation request that you can paste in a POST body to your ION node. You can/should a the minimum still leave your IPFS service running once your DID is resolvable locally if you want the DID/files you generated to be resolvable/replicated by other nodes until other nodes in the network also have the your data.

**Comment by fabianekc** [comment]
Hi @thehenrytsai, I have now ION v0.9.1 running and would like to ask the following questions:
* the IPFS service fetched a few items at the start but does not receive anything afterwards so far; especially, I receive a 404 when running `curl http://localhost:3000/identifiers/did:ion:test:EiAc5-UlFot7NtK9Nq8Qc_iVQds8n78zO3gE2bUuZdOIlA` - how long should one typically wait until the example can be resolved?        
* I did run successfully `ion operation create` from the CLI documentation - can you provide some example commands on how to publish the DID operation?

@frankhinek I updated https://github.com/ownyourdata/did-ion with the current version from ION and included some insights from this thread. I'll continue to experiment with creating DIDs on ION and look forward to any feedback or suggestions!

**Comment by fabianekc** [comment]
2 days later with continuously running core services on v0.9.1:
* still not able to resove `did:ion:test:EiAc5-UlFot7NtK9Nq8Qc_iVQds8n78zO3gE2bUuZdOIlA`   
* IPFS just outputs repeatedly:    
```
Handling fetch request for 'EiCVsEpb5QZ4yVjz_vIoULuWyXHNUzCTR4-_DOdGO4T7Ng'...
Handling fetch request for 'EiAZAq4xNkjNPcdlz3tnR6Hy5hgE3z_dqXic2sDjinmw-g'...
Handling fetch request for 'EiANulBm6EmDwtpa2KKGHoMT_YALil5a6qsXTSMSIMS41A'...
Handling fetch request for 'EiD-K2HvnyFTTLFCesLJT9wdZSS3qk6xjtUOz5AvGKqIiw'...
Handling fetch request for 'EiBCUDGpXINBvwPSBUxyXRAppTvSCtgcX1aLT-uapJLSYA'...
Handling fetch request for 'EiC0O2u1ESgx4ouLa8_ZPjN7krePuumfeGonw7SIYk_TFA'...
Handling fetch request for 'EiC0O2u1ESgx4ouLa8_ZPjN7krePuumfeGonw7SIYk_TFA'...
Handling fetch request for 'EiCGYX4qrF1MX3sdrx9QMGNX2CWnnFqsBeL79MNRcmmP6g'...
Handling fetch request for 'EiDWVjf1xZPcnJsr9voJP4RDwaZ-p1M5-V-gnXjQyVoHGw'...
'EiCVsEpb5QZ4yVjz_vIoULuWyXHNUzCTR4-_DOdGO4T7Ng' not found on IPFS.
'EiAZAq4xNkjNPcdlz3tnR6Hy5hgE3z_dqXic2sDjinmw-g' not found on IPFS.
'EiANulBm6EmDwtpa2KKGHoMT_YALil5a6qsXTSMSIMS41A' not found on IPFS.
'EiD-K2HvnyFTTLFCesLJT9wdZSS3qk6xjtUOz5AvGKqIiw' not found on IPFS.
'EiBCUDGpXINBvwPSBUxyXRAppTvSCtgcX1aLT-uapJLSYA' not found on IPFS.
'EiC0O2u1ESgx4ouLa8_ZPjN7krePuumfeGonw7SIYk_TFA' not found on IPFS.
'EiC0O2u1ESgx4ouLa8_ZPjN7krePuumfeGonw7SIYk_TFA' not found on IPFS.
'EiCGYX4qrF1MX3sdrx9QMGNX2CWnnFqsBeL79MNRcmmP6g' not found on IPFS.
'EiDWVjf1xZPcnJsr9voJP4RDwaZ-p1M5-V-gnXjQyVoHGw' not found on IPFS.
```

Any suggestions what might be wrong?

**Comment by csuwildcat** [comment]
Can you please try the v1 node, and if there is still an issue, file another issue?
